Add dynamic installation directory handling and improve README options

diff --git a/psychopy_linux_installer b/psychopy_linux_installer
--- a/psychopy_linux_installer
+++ b/psychopy_linux_installer
@@ -38,15 +38,15 @@ show_help() {
             "  --psychopy-version=VERSION                    Specify PsychoPy version (default: ${DEFAULT_OPTS[PSYCHOPY_VERSION]})." \
             "  --python-version=3.8|3.9|3.10                 Specify Python version (default: ${DEFAULT_OPTS[PYTHON_VERSION]})." \
             "  --wxpython-version=VERSION                    Specify wxPython version (default: ${DEFAULT_OPTS[WXPYTHON_VERSION]})." \
-            "  --requirements-file=FILE                      Specify a requirements.txt file to define dependencies." \
-            "  --build=[python|wxpython|both]                Build Python and/or wxPython from source instead of downloading. Not recommended, only use if installation doesn't work as expected." \
             "  --install-dir=DIR                             Specify installation directory (default: \"${DEFAULT_OPTS[INSTALL_DIR]}\")." \
-            "  --venv-name=NAME                              Specify a custom name for the virtual environment folder. If omitted, a versioned subdirectory will be used by default." \
-            "  --additional-packages=PACKAGES                Specify additional pip packages to install. Format: package1==version,package2." \
+            "  --venv-name=NAME                              Specify a custom name for the virtual environment folder. If omitted, a versioned subdirectory will be used by default. If installing into the default --install-dir, the name cannot be 'python' (case-insensitive)." \
+            "  --additional-packages=PKG,PKG,...             Specify additional pip packages to install. Format: package1==version,package2." \
+            "  --requirements-file=FILE                      Install all pip packages from FILE (e.g. a requirements.txt generated by the PsychoPy BIDS plugin) into the PsychoPy virtual environment." \
+            "  --build=[python|wxpython|both]                Build Python and/or wxPython from source instead of downloading. Not recommended, only use if installation doesn't work as expected." \
             "  --sudo-mode=[ask|auto|error|continue|force]   Control sudo usage. ask: confirm, auto: auto-confirm, error: exit if sudo needed, continue: continue without sudo, force: use sudo directly (default: ${DEFAULT_OPTS[SUDO_MODE]})." \
+            "  --non-interactive                             Run the installer without user interaction. Sets sudo-mode to auto if not set." \
             "  --disable-shortcut                            Disable desktop shortcut creation." \
             "  --disable-path                                Disable adding PsychoPy to system path." \
-            "  --non-interactive                             Run the installer without user interaction. Sets sudo-mode to auto if not set." \
             "  --remove-psychopy-settings                    Remove existing PsychoPy user settings (${HOME}/.psychopy3). Retaining this folder can sometimes result in conflicts with plugins or non-default pip-installed packages." \
             "  --gui                                         Launches the installer in GUI mode, allowing you to set arguments interactively. Any arguments provided via the command line will be ignored while in GUI mode." \
             "  -f, --force-overwrite                         Force overwrite of existing installation directory." \
@@ -137,6 +137,12 @@ process_arguments() {
         --wxpython-version=*)
             WXPYTHON_VERSION="${arg#*=}"
             ;;
+        --install-dir=*)
+            INSTALL_DIR="${arg#*=}"
+            ;;
+        --venv-name=*)
+            VENV_NAME="${arg#*=}"
+            ;;
         --additional-packages=*)
             ADDITIONAL_PACKAGES="${arg#*=}"
             ;;
@@ -162,12 +168,6 @@ process_arguments() {
                 ;;
             esac
             ;;
-        --install-dir=*)
-            INSTALL_DIR="${arg#*=}"
-            ;;
-        --venv-name=*)
-            VENV_NAME="${arg#*=}"
-            ;;
         --sudo-mode=*)
             SUDO_MODE="${arg#*=}"
             if [[ "${SUDO_MODE}" != "ask" && "${SUDO_MODE}" != "continue" && "${SUDO_MODE}" != "auto" && "${SUDO_MODE}" != "error" && "${SUDO_MODE}" != "force" ]]; then
@@ -175,20 +175,22 @@ process_arguments() {
             fi
             sudo_mode_set=true
             ;;
-        --disable-shortcut)
-            DISABLE_SHORTCUT=true
-            ;;
-        --disable-path)
-            DISABLE_PATH=true
-            ;;
         --non-interactive)
             NON_INTERACTIVE=true
             if [ "${sudo_mode_set}" = false ]; then
                 SUDO_MODE=auto
             fi
             ;;
+        --disable-shortcut)
+            DISABLE_SHORTCUT=true
+            ;;
+        --disable-path)
+            DISABLE_PATH=true
+            ;;
         --remove-psychopy-settings)
             REMOVE_PSYCHOPY_SETTINGS=true
+            ;;
+        --gui)
             ;;
         -f | --force-overwrite)
             FORCE_OVERWRITE=true
@@ -222,7 +224,7 @@ show_gui() {
 
     # Prompt for custom virtual environment name
     if VENV_NAME=$(zenity --entry --title="Custom Virtual Environment Name (optional)" --width=800 --height=500 \
-        --text="Enter a custom name for the virtual environment folder.\n\nIf left blank, the default versioned name will be used: PsychoPy-{PSYCHOPY_VERSION}-Python{PYTHON_VERSION}.\n\nThis folder will be created inside:\n${INSTALL_DIR}\n\nNote: Spaces in the name will be replaced with underscores.\n\n" \
+        --text="Enter a custom name for the virtual environment folder.\n\nIf left blank, the default versioned name will be used: PsychoPy-{PSYCHOPY_VERSION}-Python{PYTHON_VERSION}.\n\nThis folder will be created inside:\n${INSTALL_DIR}\n\nNote: Spaces in the name will be replaced with underscores.\nIf installing into the default directory, the name cannot be 'python' (case-insensitive).\n\n" \
         --entry-text=""); then
         VENV_NAME=$(echo "${VENV_NAME}" | xargs)
         :
@@ -322,6 +324,13 @@ show_gui() {
         DISABLE_SHORTCUT=true
     fi
 
+    if [[ ${options} == *"Run in non-interactive mode"* ]]; then
+        NON_INTERACTIVE=true
+        SUDO_MODE=auto
+    else
+        NON_INTERACTIVE=false
+    fi
+
     if [[ ${options} == *"Force overwrite of existing directory"* ]]; then
         FORCE_OVERWRITE=true
     fi
@@ -342,13 +351,7 @@ show_gui() {
         VERBOSE=true
     fi
 
-    if [[ ${options} == *"Run in non-interactive mode"* ]]; then
-        NON_INTERACTIVE=true
-        SUDO_MODE=auto
-    else
-        NON_INTERACTIVE=false
-    fi
-
+    # Sudo mode selection
     if [[ ${NON_INTERACTIVE} == false ]]; then
         if SUDO_MODE=$(zenity --list --title="Sudo Mode" --width=800 --height=500 \
             --text="Select the desired sudo mode:\n\n \
@@ -464,12 +467,7 @@ parse_requirements_file() {
 
     [[ -z "${PYTHON_VERSION}" ]] && log_message "WARNING: Python version not specified in the requirements file; using default: '${DEFAULT_OPTS[PYTHON_VERSION]}'."
     [[ -z "${WXPYTHON_VERSION}" ]] && log_message "WARNING: wxPython version not specified in the requirements file; using default: '${DEFAULT_OPTS[WXPYTHON_VERSION]}'."
-
-    if [ -z "${PSYCHOPY_VERSION}" ]; then
-        log_message "ERROR: psychopy version not specified in requirements.txt." nolog
-    else
-        REQUIREMENTSFILE_PACKAGES="${REQUIREMENTSFILE_PACKAGES:+${REQUIREMENTSFILE_PACKAGES},}psychopy==${PSYCHOPY_VERSION}"
-    fi
+    [[ -z "${PSYCHOPY_VERSION}" ]] && log_message "WARNING: psychopy version not specified in the requirements file; using default: '${DEFAULT_OPTS[PSYCHOPY_VERSION]}'."
 
     # Adjust Linux dependencies
     for pkg in pyglet python-vlc; do
@@ -618,7 +616,7 @@ check_script_update() {
         echo -e "\nA new version (${latest_version}) of the installer script is available."
         echo "    🔹 Repository: https://github.com/wieluk/psychopy_linux_installer"
         echo "    🔹 Releases:   https://github.com/wieluk/psychopy_linux_installer/releases"
-        echo "    🔹 Issues:   https://github.com/wieluk/psychopy_linux_installer/issues"
+        echo "    🔹 Issues:     https://github.com/wieluk/psychopy_linux_installer/issues"
         echo
 
         local script_path
@@ -902,6 +900,30 @@ filter_installable_packages() {
     echo "${filtered_packages[@]}"
 }
 
+install_pip_packages_with_fallback() {
+    local packages_csv="$1"
+    local pkg_name installed_version
+
+    log_message "INFO: Installing extra pip packages from --additional-packages and/or --requirements-file."
+
+    if log "${PYTHON_VENV_COMMAND}" -m pip install -r <(echo "${packages_csv}"); then
+        log_message "INFO: All packages installed successfully."
+    else
+        log_message "WARNING: Failed to install some packages. Installing one by one ..."
+        IFS=',' read -ra PACKAGES <<<"${packages_csv}"
+        for package in "${PACKAGES[@]}"; do
+            log_message "INFO: Installing '${package}' ..."
+            if log "${PYTHON_VENV_COMMAND}" -m pip install "${package}"; then
+                pkg_name="${package%%=*}"
+                installed_version=$("${PYTHON_VENV_COMMAND}" -m pip show "${pkg_name}" | grep Version | cut -d' ' -f2)
+                log_message "INFO: '${pkg_name}' version '${installed_version}' installed successfully."
+            else
+                log_message "WARNING: Failed to install '${package}'. Skipping."
+            fi
+        done
+    fi
+}
+
 # Verifies if the specific Python version is available through the package manager.
 check_python_in_package_manager() {
     local available_version
@@ -963,19 +985,6 @@ get_latest_pypi_version() {
     declare -n result=${var_name}
     # shellcheck disable=SC2034
     result="${version}"
-}
-
-# Converts a PsychoPy package spec to the appropriate Git URL if needed.
-convert_psychopy_req_to_git_url() {
-    local package_spec="${1}"
-
-    if [[ ! ${package_spec} =~ ^psychopy== ]] || [ "${PSYCHOPY_GIT_TAG}" != "true" ]; then
-        echo "${package_spec}"
-        return 0
-    fi
-
-    local version=${package_spec#psychopy==}
-    echo "git+https://github.com/psychopy/psychopy.git@${version}"
 }
 
 # Verifies that the requested package version exists on PyPI (or Git).
@@ -1044,7 +1053,7 @@ build_python() {
     cd "${temp_dir}/Python-${latest_patch_version}" || {
         log_message "ERROR: Failed to change directory."
     }
-    log ./configure --enable-optimizations --with-ensurepip=install --prefix=/usr/local/psychopy/python
+    log ./configure --enable-optimizations --with-ensurepip=install --prefix="${DEFAULT_OPTS[INSTALL_DIR]}/python"
     log make -j "$(nproc)"
     sudo_wrapper make altinstall
     cd "${PSYCHOPY_DIR}" || {
@@ -1171,9 +1180,9 @@ install_wxpython_from_github() {
         mv "${wheel_name}" "${renamed_wheel}"
         if log "${PYTHON_VENV_COMMAND}" -m pip install "${renamed_wheel}"; then
             log_message "INFO: Installed wxPython from '${renamed_wheel}'"
-            sudo_wrapper mkdir -p /usr/local/psychopy/python/wx_wheels
-            sudo_wrapper chmod -R a+rX /usr/local/psychopy/python/wx_wheels
-            sudo_wrapper mv "${renamed_wheel}" /usr/local/psychopy/python/wx_wheels/
+            sudo_wrapper mkdir -p "${DEFAULT_OPTS[INSTALL_DIR]}/python/wx_wheels"
+            sudo_wrapper chmod -R a+rX "${DEFAULT_OPTS[INSTALL_DIR]}/python/wx_wheels"
+            sudo_wrapper mv "${renamed_wheel}" "${DEFAULT_OPTS[INSTALL_DIR]}/python/wx_wheels/"
             return 0
         else
             log_message "WARNING: Installing wxPython from '${renamed_wheel}' failed."
@@ -1278,7 +1287,7 @@ add_psychopy_to_path() {
 }
 
 main() {
-    local use_gui tmp_log_file final_log_file rerun_cmd
+    local use_gui tmp_log_file final_log_file rerun_cmd pip_extra_packages
     PKG_MANAGER_PERMISSION=false
     PSYCHOPY_GIT_TAG=false
     TEMPORARY_SUDO_SETUP_DONE=false
@@ -1324,6 +1333,9 @@ main() {
     done
 
     VENV_NAME=${VENV_NAME//[[:space:]]/_}
+    if [[ "${INSTALL_DIR}" == "${DEFAULT_OPTS[INSTALL_DIR]}" && "${VENV_NAME,,}" == "python" ]]; then
+        log_message "ERROR: The virtual environment name cannot be 'python' (case-insensitive) when installing into the default directory ('${DEFAULT_OPTS[INSTALL_DIR]}')." nolog
+    fi
 
     if ${use_gui}; then
         rerun_cmd=$(create_rerun_command)
@@ -1408,8 +1420,8 @@ main() {
             install_dependencies python_build_deps
             build_python
         else
-            if [ -x "/usr/local/psychopy/python/bin/python${PYTHON_VERSION}" ]; then
-                log_message "INFO: 'Python${PYTHON_VERSION}' is already installed in '/usr/local/psychopy/python'. Skipping installation."
+            if [ -x "${DEFAULT_OPTS[INSTALL_DIR]}/python/bin/python${PYTHON_VERSION}" ]; then
+                log_message "INFO: 'Python${PYTHON_VERSION}' is already installed in '${DEFAULT_OPTS[INSTALL_DIR]}/python'. Skipping installation."
             else
                 log_message "INFO: Installing Python build dependencies ..."
                 install_dependencies python_build_deps
@@ -1421,12 +1433,12 @@ main() {
             fi
         fi
 
-        check_python_env "/usr/local/psychopy/python/bin/python${PYTHON_VERSION}"
-        if [ ! -x "/usr/local/psychopy/python/bin/python${PYTHON_VERSION}" ]; then
-            log_message "ERROR: 'python${PYTHON_VERSION}' not found in '/usr/local/psychopy/python'. Something went wrong while installing/building. You can try '--build=python'."
+        check_python_env "${DEFAULT_OPTS[INSTALL_DIR]}/python/bin/python${PYTHON_VERSION}"
+        if [ ! -x "${DEFAULT_OPTS[INSTALL_DIR]}/python/bin/python${PYTHON_VERSION}" ]; then
+            log_message "ERROR: 'python${PYTHON_VERSION}' not found in '${DEFAULT_OPTS[INSTALL_DIR]}/python'. Something went wrong while installing/building. You can try '--build=python'."
         fi
-        export PATH=/usr/local/psychopy/python/bin:$PATH
-        /usr/local/psychopy/python/bin/python"${PYTHON_VERSION}" -m venv "${PSYCHOPY_DIR}"
+        export PATH=${DEFAULT_OPTS[INSTALL_DIR]}/python/bin:$PATH
+        "${DEFAULT_OPTS[INSTALL_DIR]}"/python/bin/python"${PYTHON_VERSION}" -m venv "${PSYCHOPY_DIR}"
     else
         log_message "INFO: 'Python${PYTHON_VERSION}' can be installed via package manager. Installing ..."
         install_dependencies python_with_venv
@@ -1463,7 +1475,7 @@ main() {
     elif [ "${BUILD_WX}" = true ]; then
         build_wxpython
     else
-        if log "${PYTHON_VENV_COMMAND}" -m pip install --only-binary=:all: --find-links /usr/local/psychopy/python/wx_wheels/ "wxpython==${WXPYTHON_VERSION}"; then
+        if log "${PYTHON_VENV_COMMAND}" -m pip install --only-binary=:all: --find-links "${DEFAULT_OPTS[INSTALL_DIR]}/python/wx_wheels/" "wxpython==${WXPYTHON_VERSION}"; then
             log_message "INFO: Successfully installed wxPython '${WXPYTHON_VERSION}' from local wheel."
         elif log "${PYTHON_VENV_COMMAND}" -m pip install --only-binary=:all: --find-links "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/${OS_VERSION_LINK}/" "wxPython==${WXPYTHON_VERSION}"; then
             log_message "INFO: Successfully installed wxPython '${WXPYTHON_VERSION}' from extras.wxpython.org."
@@ -1478,58 +1490,23 @@ main() {
         log_message "ERROR: wxPython is not installed. Something went wrong during the installation. You can try '--build=wxpython'."
     fi
 
-    if [ -n "${REQUIREMENTS_FILE}" ]; then
-        log_message "INFO: Installing packages from requirements file ..."
-        transformed_packages=$(echo "${REQUIREMENTSFILE_PACKAGES}" | tr ',' '\n' | while read -r pkg; do
-            convert_psychopy_req_to_git_url "${pkg}"
-        done)
+    # Install additional packages from requirements file and flag
+    pip_extra_packages="${ADDITIONAL_PACKAGES}${ADDITIONAL_PACKAGES:+,}${REQUIREMENTSFILE_PACKAGES}"
 
-        if log "${PYTHON_VENV_COMMAND}" -m pip install -r <(echo "${transformed_packages}"); then
-            log_message "INFO: Packages from '${REQUIREMENTS_FILE}' installed successfully."
-        else
-            log_message "WARNING: Failed to install packages from '${REQUIREMENTS_FILE}'. Installing packages one by one ..."
-            IFS=',' read -ra PACKAGES <<<"${REQUIREMENTSFILE_PACKAGES}"
-            for package in "${PACKAGES[@]}"; do
-                log_message "INFO: Installing '${package}' ..."
-                transformed_pkg=$(convert_psychopy_req_to_git_url "${package}")
-                if log "${PYTHON_VENV_COMMAND}" -m pip install "${transformed_pkg}"; then
-                    pkg_name="${package%%=*}"
-                    installed_version=$("${PYTHON_VENV_COMMAND}" -m pip show "${pkg_name}" | grep Version | cut -d' ' -f2)
-                    log_message "INFO: '${pkg_name}' version '${installed_version}' installed successfully."
-                else
-                    log_message "WARNING: Failed to install '${package}'. Skipping."
-                fi
-            done
-        fi
+    [ -n "${pip_extra_packages}" ] && install_pip_packages_with_fallback "${pip_extra_packages}"
+
+    # Install PsychoPy
+    log_message "INFO: Installing PsychoPy '${PSYCHOPY_VERSION}' ..."
+    if [ "${PSYCHOPY_VERSION}" == "git" ]; then
+        log "${PYTHON_VENV_COMMAND}" -m pip install git+https://github.com/psychopy/psychopy.git@dev
+    elif [ "${PSYCHOPY_GIT_TAG}" = "true" ]; then
+        log "${PYTHON_VENV_COMMAND}" -m pip install "git+https://github.com/psychopy/psychopy.git@${PSYCHOPY_VERSION}"
     else
-        # Install PsychoPy
-        log_message "INFO: Installing PsychoPy '${PSYCHOPY_VERSION}' ..."
-        if [ "${PSYCHOPY_VERSION}" == "git" ]; then
-            log "${PYTHON_VENV_COMMAND}" -m pip install git+https://github.com/psychopy/psychopy.git@dev
-        elif [ "${PSYCHOPY_GIT_TAG}" = "true" ]; then
-            log "${PYTHON_VENV_COMMAND}" -m pip install "git+https://github.com/psychopy/psychopy.git@${PSYCHOPY_VERSION}"
-        else
-            log "${PYTHON_VENV_COMMAND}" -m pip install psychopy=="${PSYCHOPY_VERSION}"
-        fi
-
-        if ! "${PYTHON_VENV_COMMAND}" -m pip show psychopy &>/dev/null; then
-            log_message "ERROR: PsychoPy installation failed."
-        fi
+        log "${PYTHON_VENV_COMMAND}" -m pip install psychopy=="${PSYCHOPY_VERSION}"
     fi
 
-    # Install additional packages if specified
-    if [ -n "${ADDITIONAL_PACKAGES}" ]; then
-        log_message "INFO: Installing additional packages ..."
-        IFS=',' read -ra PACKAGES <<<"${ADDITIONAL_PACKAGES}"
-        for package in "${PACKAGES[@]}"; do
-            log_message "INFO: Installing '${package}' ..."
-            if log "${PYTHON_VENV_COMMAND}" -m pip install "${package}"; then
-                installed_version=$("${PYTHON_VENV_COMMAND}" -m pip show "${package%%=*}" | grep Version | cut -d' ' -f2)
-                log_message "INFO: '${package%%=*}' version '${installed_version}' installed successfully."
-            else
-                log_message "WARNING: Failed to install '${package}'. Skipping."
-            fi
-        done
+    if ! "${PYTHON_VENV_COMMAND}" -m pip show psychopy &>/dev/null; then
+        log_message "ERROR: PsychoPy installation failed."
     fi
 
     # Install numpy<2 if PsychoPy version is less than 2024.2.0
