create functions to build wxpython and add more consistent comments

diff --git a/psychopy_linux_installer b/psychopy_linux_installer
--- a/psychopy_linux_installer
+++ b/psychopy_linux_installer
@@ -4,12 +4,11 @@
 #  Description:   This script installs PsychoPy with specified versions of
 #                 Python, wxPython, and optional packages.
 #  Author:        Lukas Wiertz
-#  Date:          2024-10-11
-#  Version:       1.1.4
+#  Date:          2024-10-19
+#  Version:       1.1.5
 #  License:       GNU General Public License v3.0
 # ==============================================================================
 
-# Function to show help message
 show_help() {
     cat << EOF
 Usage: ./psychopy_linux_installer [options]
@@ -50,18 +49,15 @@ sudo_wrapper() {
         local exit_code=$1
         local error_output=$2
 
-        # Check for common exit codes indicating permission errors
         case $exit_code in
             13|77|100|126|127) return 0 ;;
         esac
 
-        # Check for common error messages indicating permission errors
         if [[ $exit_code -ne 0 ]]; then
             echo "$error_output" | grep -Eqi "permission denied|requires root|must be root|not authorized|could not open|operation not permitted|cannot open|superuser privileges|has to be run with|error: must run as root|unless you are root|root privileges are required|eacces|eperm|not allowed|need root|failed to open|permission problem|permission error|not permitted|cannot access|cannot create|cannot remove|cannot write|read-only file system|you don't have the right|do not have the required permissions|cannot execute"
         fi
     }
 
-    # Function to handle sudo requests based on the sudo_mode
     handle_sudo_request() {
         local command=("$@")
         local response
@@ -114,7 +110,6 @@ sudo_wrapper() {
         return
     fi
 
-    # Execute the command and capture its output and exit code
     error_output=$("${command[@]}" 2>&1)
     exit_code=$?
     
@@ -130,6 +125,7 @@ log_message() {
     echo "$(date "+%Y-%m-%d %H:%M:%S") - $1"
 }
 
+# Function to detect OS of machine
 detect_os_version() {
     if [ -f /etc/os-release ]; then
         . /etc/os-release
@@ -165,6 +161,7 @@ detect_os_version() {
         return
     fi
 
+    log_message "Error: Unable to detect OS version."
     exit 1
 }
 
@@ -181,7 +178,8 @@ detect_package_manager() {
     elif command -v zypper > /dev/null 2>&1; then
         echo "zypper"
     else
-        echo "none"
+        log_message "Error: No compatible package manager found. Exiting."
+        exit 1
     fi
 }
 
@@ -193,7 +191,7 @@ update_package_manager() {
         dnf) sudo_wrapper dnf check-update -q ;;
         pacman) sudo_wrapper pacman -Sy --noconfirm ;;
         zypper) sudo_wrapper zypper refresh ;;
-        *) log_message "No compatible package manager found."; exit 1 ;;
+        *) log_message "Error: No compatible package manager found."; exit 1 ;;
     esac
 }
 
@@ -208,7 +206,7 @@ install_packages() {
             dnf) sudo_wrapper dnf install -y -q "$package" || log_message "Package $package not found, skipping." ;;
             pacman) sudo_wrapper pacman -Sy --noconfirm "$package" || log_message "Package $package not found, skipping." ;;
             zypper) sudo_wrapper zypper install -y "$package" || log_message "Package $package not found, skipping." ;;
-            *) log_message "No compatible package manager found."; exit 1 ;;
+            *) log_message "Error: No compatible package manager found."; exit 1 ;;
         esac
     done
 }
@@ -218,7 +216,6 @@ install_dependencies() {
     local dep_type=$1
     local dependencies=()
 
-    # Define dependencies for different package managers
     case $pkg_manager in
         apt-get)
             script_deps=(git curl jq)
@@ -245,10 +242,9 @@ install_dependencies() {
             wxpython_deps=(libpng16-devel gstreamer-plugins-base freeglut-devel libnotify-devel libSM-devel gtk2-devel gcc-c++ make)
             ;;
         *)
-            log_message "No compatible package manager found."; exit 1 ;;
+            log_message "Error: No compatible package manager found."; exit 1 ;;
     esac
     
-    # Set the list of dependencies based on the type requested
     case $dep_type in
         script_deps) dependencies=("${script_deps[@]}") ;;
         python_build_deps) dependencies=("${python_build_deps[@]}") ;;
@@ -257,7 +253,6 @@ install_dependencies() {
         *) log_message "Invalid dependency type specified."; exit 1 ;;
     esac
 
-    # Install the dependencies
     install_packages "${dependencies[@]}"
 }
 
@@ -274,7 +269,7 @@ version_greater_than() {
 check_python_version() {
     local version=$1
     if ! curl -s --head --fail "https://www.python.org/ftp/python/${version}/Python-${version}.tgz" > /dev/null; then
-        log_message "Python version ${version} does not exist. Exiting."
+        log_message "Error: Python version ${version} does not exist. Exiting."
         exit 1
     fi
 }
@@ -285,7 +280,7 @@ get_latest_pypi_version() {
     local latest_version
     latest_version=$(curl -s "https://pypi.org/pypi/${package_name}/json" | jq -r .info.version)
     if [ -z "$latest_version" ]; then
-        log_message "Unable to fetch the latest version for package ${package_name}. Exiting."
+        log_message "Error: Unable to fetch the latest version for package ${package_name}. Exiting."
         exit 1
     fi
     echo "$latest_version"
@@ -296,7 +291,7 @@ check_pypi_for_version() {
     local package=$1
     local version=$2
     if ! curl -s "https://pypi.org/pypi/${package}/${version}/json" | jq -e .info.version > /dev/null; then
-        log_message "${package} version ${version} does not exist. Exiting."
+        log_message "Error: ${package} version ${version} does not exist. Exiting."
         exit 1
     fi
 }
@@ -344,14 +339,38 @@ download_prebuilt_python() {
         )
         sudo_wrapper rm -rf "${temp_dir}" "${temp_file}"
     else
-        log_message "Failed to download from Nextcloud. No matching Python version found."
+        log_message "Warning: Failed to download from Nextcloud. No matching Python version found."
         build_python_from_source "${python_version}"
     fi
 }
 
-# Function to get the URL for the wxPython wheel
-get_wxpython_wheel() {
-    local wxpython_version=$1
+# Function to build wxPython from source
+build_wxpython() {
+    log_message "Installing wxPython build dependencies. This might take a while ..."
+    install_dependencies wxpython_deps
+
+    log_message "Building wxPython $wxpython_version from source. This might take a while ..."
+    if pip install --no-binary=:all: "wxpython==$wxpython_version"; then
+        log_message "Successfully built wxPython from source."
+    else
+        log_message "Error: Building wxPython from source failed."
+        exit 1
+    fi
+}
+
+# Function install wxPython using pip without building
+wxpython_pip_install() {
+    if log pip install --only-binary=:all: "wxpython==$wxpython_version"; then
+        log_message "Successfully installed wxPython version $wxpython_version using a pip wheel."
+        return 0
+    else
+        log_message "Pip install with --only-binary failed."
+        return 1
+    fi
+}
+
+# Function to install wxPython from wheel URL
+wxpython_wheelurl_install() {
     local base_url="https://extras.wxpython.org/wxPython4/extras/linux/gtk3/"
     local wheel_dir
     local python_version_short
@@ -359,6 +378,7 @@ get_wxpython_wheel() {
     local wheels
     local latest_wheel
     local wheel_url
+    local wheel_file
 
     wheel_dir="${base_url}${os_version}/"
     python_version_short=$(python -c "import sys; print('cp' + ''.join(map(str, sys.version_info[:2])))")
@@ -373,20 +393,50 @@ get_wxpython_wheel() {
 
     latest_wheel=$(echo "$wheels" | tail -n 1)
     wheel_url="${wheel_dir}${latest_wheel}"
+    wheel_file=$(basename "$wheel_url")
 
-    echo "$wheel_url"
-    return 0
-}
-# Function to build wxPython from source
-build_wxpython() {
-    log_message "Installing wxPython build dependencies. This might take a while ..."
-    install_dependencies wxpython_deps
-
-    log_message "Building wxPython $wxpython_version from source. This might take a while ..."
-    if pip install --no-binary=:all: "wxpython==$wxpython_version"; then
-        log_message "Successfully built wxPython from source."
+    log_message "Found matching wxPython wheel; downloading it from extras.wxpython.org ($wheel_url)"
+    if log curl -s -O "$wheel_url"; then
+        log_message "Download successful. Installing wxPython from $wheel_file..."
+        if log pip install "$wheel_file"; then
+            log_message "Installed wxPython from $wheel_file"
+            sudo_wrapper rm "$wheel_file"
+            return 0
+        else
+            log_message "Warning: Installing wxPython from $wheel_file failed."
+            sudo_wrapper rm "$wheel_file"
+            return 1
+        fi
     else
-        log_message "Error: Building wxPython from source failed."
+        log_message "Warning: Downloading $wheel_url failed."
+        return 1
+    fi
+}
+
+# Function to install wxPython from Nextcloud
+wxpython_nextcloud_install() {
+    python_major=$(python -c "import sys; print(sys.version_info.major)")
+    python_minor=$(python -c "import sys; print(sys.version_info.minor)")
+    wheel_name="wxPython-${wxpython_version}-cp${python_major}${python_minor}-cp${python_major}${python_minor}-${processor_structure}-${os_version}.whl"
+    wx_python_nextcloud_url="https://cloud.uni-graz.at/index.php/s/YtX33kbasHMZdgs/download?path=${wheel_name}"
+
+    log_message "Trying to download wxPython wheel from Nextcloud ($wx_python_nextcloud_url)"
+    if log curl -f -X GET "$wx_python_nextcloud_url" --output "$wheel_name"; then
+        wx_python_file="${wheel_name%-"${os_version}".whl}.whl"
+        mv "$wheel_name" "$wx_python_file"
+        log_message "Download successful. Installing wxPython from $wx_python_file"
+        if log pip install "$wx_python_file"; then
+            log_message "Installed wxPython from $wx_python_file"
+            sudo_wrapper rm "$wx_python_file"
+            return 0
+        else
+            log_message "Warning: Installing wxPython from Nextcloud failed."
+            sudo_wrapper rm "$wx_python_file"
+            return 1
+        fi
+    else
+        log_message "Warning: Downloading from Nextcloud failed."
+        return 1
     fi
 }
 
@@ -512,10 +562,7 @@ add_psychopy_to_path() {
     echo "${psychopy_dir}/bin/psychopy"
 }
 
-
-
 main() {
-    # Set default values for variables
     python_version="3.10.15"
     python_version_set_by_user=false
     psychopy_version="2024.1.4"
@@ -534,7 +581,6 @@ main() {
     disable_shortcut=false
     disable_path=false
 
-    # Parse command line arguments
     for arg in "$@"; do
         case $arg in
             --python-version=*)
@@ -579,7 +625,7 @@ main() {
                         build_wx=true
                         ;;
                     *)
-                        echo "Invalid option for --build: $build_arg"
+                        echo "Error: Invalid option for --build: $build_arg"
                         show_help
                         exit 1
                         ;;
@@ -609,14 +655,12 @@ main() {
                 exit 0
                 ;;
             *)
-                echo "Unknown option: $arg"
+                echo "Error: Unknown option: $arg"
                 show_help
                 exit 1
                 ;;
         esac
     done
-
-
 
     # Detect OS version and architecture
     os_version=$(detect_os_version | tr '[:upper:]' '[:lower:]')
@@ -625,10 +669,6 @@ main() {
 
     # Detect package manager
     pkg_manager=$(detect_package_manager)
-    if [ "$pkg_manager" == "none" ]; then
-        log_message "No compatible package manager found. Exiting."
-        exit 1
-    fi
 
     # Update package manager
     log_message "Updating ${pkg_manager} package manager."
@@ -660,9 +700,8 @@ main() {
     else
         check_python_version "${python_version}"
     fi
-
-    # Clean up Python version string
     python_version_clean=$(echo "${python_version}" | tr -d ',;')
+    
     # Set up PsychoPy installation directory
     if [ "$no_versioned_install_dir" = true ]; then
         psychopy_dir="${install_dir}"
@@ -676,7 +715,7 @@ main() {
             sudo_wrapper rm -rf "${psychopy_dir}"
             sudo_wrapper mkdir -p "${psychopy_dir}"
         else
-            log_message "Directory ${psychopy_dir} already exists. Use the --force flag to overwrite. Exiting."
+            log_message "Error: Directory ${psychopy_dir} already exists. Use the --force flag to overwrite. Exiting."
             exit 1
         fi
     else
@@ -687,16 +726,9 @@ main() {
     #Check if psychopy_dir is writeable else change ownership 
     [ -w "${psychopy_dir}" ] || sudo_wrapper chown "$USER" "${psychopy_dir}"
 
-    #Exit script if writing or cd to psychopy_dir is not possible
-    if [ -w "${psychopy_dir}" ]; then
-        if cd "${psychopy_dir}"; then
-            :
-        else
-            log_message "Failed to change directory to ${psychopy_dir}. Exiting."
-            exit 1
-        fi
-    else
-        log_message "Cannot write to ${psychopy_dir}. Exiting."
+    # Exit script if writing or changing directory to psychopy_dir is not possible
+    if ! [ -w "${psychopy_dir}" ] || ! cd "${psychopy_dir}"; then
+        log_message "Error: Failed to access or change directory to ${psychopy_dir}. Exiting."
         exit 1
     fi
 
@@ -742,50 +774,21 @@ main() {
     fi
 
     if [ "$wxpython_version" = "git" ]; then
-        log_message "Installing wxpython build dependencies. This might take a while ..."
+        log_message "Installing wxPython build dependencies. This might take a while ..."
         install_dependencies wxpython_deps
         log_message "Building wxPython from git. This might take a while ..."
         log pip install git+https://github.com/wxWidgets/Phoenix
     elif [ "$build_wx" = true ]; then
         build_wxpython
     else
-        if log pip install --only-binary=:all: "wxpython==$wxpython_version"; then
-            log_message "Successfully installed wxPython version $wxpython_version using a pip wheel."
-        elif wheel_url=$(get_wxpython_wheel "$wxpython_version"); then
-            wheel_file=$(basename "$wheel_url")
-            log_message "Found matching wxPython wheel; downloading it from extras.wxpython.org ($wheel_url)"
-            log curl -s -O "$wheel_url"
-            log_message "Download successful. Installing wxPython from $wheel_file..."
-            if log pip install "$wheel_file"; then
-                log_message "Installed wxPython from $wheel_file"
-                sudo_wrapper rm "$wheel_file"
-            else
-                log_message "Error: Installing wxPython from $wheel_file failed. Attempting to build from source."
-                build_wxpython
-            fi
+        if wxpython_pip_install; then
+            :
+        elif wxpython_wheelurl_install; then
+            :
+        elif wxpython_nextcloud_install; then
+            :
         else
-            # If no wheel is found, try downloading from Nextcloud or build from source
-            python_major=$(python -c "import sys; print(sys.version_info.major)")
-            python_minor=$(python -c "import sys; print(sys.version_info.minor)")
-
-            wheel_name="wxPython-${wxpython_version}-cp${python_major}${python_minor}-cp${python_major}${python_minor}-${processor_structure}-${os_version}.whl"
-            
-            wx_python_nextcloud_url="https://cloud.uni-graz.at/index.php/s/YtX33kbasHMZdgs/download?path=${wheel_name}"
-            
-            log_message "There is no matching wheel on wxpython.org. Trying to download wxPython wheel from Nextcloud"
-
-            if log curl -f -X GET "$wx_python_nextcloud_url" --output "$wheel_name"; then
-                wx_python_file="${wheel_name%-"${os_version}".whl}.whl"
-                mv "$wheel_name" "$wx_python_file"
-                log_message "Download successful. Installing wxPython from $wx_python_file"
-                if ! log pip install "$wx_python_file"; then
-                    log_message "Error: Installing wxPython failed. Attempting to build from source."
-                    build_wxpython
-                fi
-                sudo_wrapper rm "$wx_python_file"
-            else
-                build_wxpython
-            fi
+            build_wxpython
         fi
     fi
 
@@ -808,7 +811,6 @@ main() {
         log "Error: PsychoPy is not installed successfully. Something went wrong during the installation. Use --verbose flag."
         exit 1
     fi
-
 
     # Install additional packages if specified
     if [ -n "$additional_packages" ]; then
@@ -834,14 +836,14 @@ main() {
     sudo_wrapper usermod -a -G psychopy "$USER"
     sudo_wrapper sh -c 'echo "@psychopy - nice -20\n@psychopy - rtprio 50\n@psychopy - memlock unlimited" > /etc/security/limits.d/99-psychopylimits.conf'
 
-    # Create desktop shortcut if not disabled
+    # Create desktop shortcut
     if [ "$disable_shortcut" = false ]; then
         create_desktop_shortcut
     else
         log_message "Desktop shortcut creation disabled by user."
     fi
 
-    # Add PsychoPy to PATH if not disabled
+    # Add PsychoPy to PATH
     if [ "$disable_path" = false ]; then
         add_psychopy_to_path
     else
