Python check (#32)
* test auto detect

* run tests and force build on build_python

* add devel for headers

diff --git a/psychopy_linux_installer b/psychopy_linux_installer
--- a/psychopy_linux_installer
+++ b/psychopy_linux_installer
@@ -4,8 +4,8 @@
 #  Description:   This script installs PsychoPy with specified versions of
 #                 Python, wxPython, and optional packages.
 #  Author:        Lukas Wiertz
-#  Date:          2024-10-27
-#  Version:       1.2.1
+#  Date:          2024-10-28
+#  Version:       1.2.2
 #  License:       GNU General Public License v3.0
 # ==============================================================================
 
@@ -15,7 +15,6 @@ Usage: ./psychopy_linux_installer [options]
 Options:
   --psychopy-version=VERSION                    Specify PsychoPy version (default: 2024.1.4).
   --python-version=3.8|3.9|3.10                 Specify Python version (default: 3.10).
-  --existing-python                             Use existing Python version instead of installing a new one. Requires chosen Python version, pip, and venv to be pre-installed and accessible in the system path.
   --wxpython-version=VERSION                    Specify wxPython version (default: 4.2.2).
   --build=[python|wxpython|both]                Build Python and/or wxPython from source instead of downloading.
   --install-dir=DIR                             Specify installation directory (default: "$HOME").
@@ -226,27 +225,32 @@ install_dependencies() {
             psychopy_deps=(libgtk-3-dev libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libxcb-xinerama0 libegl1-mesa-dev libsdl2-dev libglu1-mesa-dev libusb-1.0-0-dev portaudio19-dev libasound2-dev libxcb-cursor0 libxkbcommon-x11-0)
             python_build_deps=(build-essential libssl-dev zlib1g-dev libsqlite3-dev libffi-dev libbz2-dev libreadline-dev xz-utils make)
             wxpython_deps=(libjpeg-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x freeglut3-dev libpng-dev libtiff-dev libnotify-dev libsm-dev libgtk2.0-dev g++ make)
+            python_with_venv=(python3 python3-venv python3-pip python3-dev)
             ;;
         yum|dnf)
             script_deps=(git curl jq)
             psychopy_deps=(gtk3-devel webkit2gtk3-devel libxcb-xinerama mesa-libEGL-devel SDL2-devel mesa-libGLU-devel libusb1-devel portaudio-devel alsa-lib-devel)
             python_build_deps=(gcc openssl-devel bzip2-devel libffi-devel zlib-devel sqlite-devel readline-devel xz-devel make)
             wxpython_deps=(libjpeg-devel libpng-devel libSM-devel gcc-c++ gstreamer1-plugins-base gstreamer1-devel freeglut-devel libjpeg-turbo-devel libpng-devel libtiff-devel libnotify-devel gtk2-devel make)
+            python_with_venv=(python3 python3-venv python3-pip python3-devel)
             ;;
         pacman)
             script_deps=(git curl jq)
             psychopy_deps=(gtk3 webkit2gtk libxcb mesa sdl2 glu libusb portaudio alsa-lib)
             python_build_deps=(base-devel openssl zlib sqlite libffi bzip2 readline xz make)
             wxpython_deps=(libjpeg libpng libsm mesa gstreamer gstreamer-base freeglut libtiff libnotify gtk2 gcc make)
+            python_with_venv=(python python-virtualenv python-pip)
             ;;
         zypper)
             script_deps=(git curl jq)
             psychopy_deps=(gtk3-devel libxcb-xinerama0 libSDL2-devel libusb-1_0-devel portaudio-devel alsa-devel)
             python_build_deps=(gcc libopenssl-devel zlib-devel sqlite3-devel libffi-devel bzip2-devel readline-devel xz-devel make)
             wxpython_deps=(libpng16-devel gstreamer-plugins-base freeglut-devel libnotify-devel libSM-devel gtk2-devel gcc-c++ make)
+            python_with_venv=(python3 python3-virtualenv python3-pip python3-devel)
             ;;
         *)
-            log_message "Error: No compatible package manager found."; exit 1 ;;
+            log_message "Error: No compatible package manager found."; exit 1
+            ;;
     esac
 
     case $dep_type in
@@ -254,10 +258,44 @@ install_dependencies() {
         python_build_deps) dependencies=("${python_build_deps[@]}") ;;
         psychopy_deps) dependencies=("${psychopy_deps[@]}") ;;
         wxpython_deps) dependencies=("${wxpython_deps[@]}") ;;
+        python_with_venv) dependencies=("${python_with_venv[@]}") ;;
         *) log_message "Error: Invalid dependency type specified."; exit 1 ;;
     esac
 
     install_packages "${dependencies[@]}"
+}
+
+# Function to check if python version is available in package manager
+check_python_pkg_manager() {
+    local available_version
+    
+    case $pkg_manager in
+        apt-get)
+            available_version=$(apt-cache policy python3 | grep -m 1 "Candidate:" | awk '{print $2}' | cut -d'.' -f1,2)
+            ;;
+        yum)
+            available_version=$(yum info python3 2> /dev/null | grep -m 1 Version | awk '{print $3}' | cut -d'.' -f1,2)
+            ;;
+        dnf)
+            available_version=$(dnf info python3 2> /dev/null | grep -m 1 Version | awk '{print $3}' | cut -d'.' -f1,2)
+            ;;
+        pacman)
+            available_version=$(pacman -Si python 2> /dev/null | grep -m 1 Version | awk '{print $3}' | cut -d'.' -f1,2)
+            ;;
+        zypper)
+            available_version=$(zypper info python3 2> /dev/null | grep -m 1 Version | awk '{print $3}' | cut -d'.' -f1,2)
+            ;;
+        *)
+            log_message "Error: No compatible package manager found."; exit 1
+            ;;
+    esac
+
+    if [ "$available_version" == "$python_version" ]; then
+        return 0  
+    else
+        log_message "Warning: Python $python_version not available in $pkg_manager."
+        return 1 
+    fi
 }
 
 # Function to compare version numbers
@@ -287,6 +325,25 @@ check_pypi_for_version() {
     local version=$2
     if ! curl -s "https://pypi.org/pypi/${package}/${version}/json" | jq -e .info.version > /dev/null; then
         log_message "Error: ${package} version ${version} does not exist. Exiting."
+        exit 1
+    fi
+}
+
+# Function to check if python is in path and pip and venv are installed
+check_python_env() {
+    local python_cmd="$1"
+    if ! command -v "$python_cmd" > /dev/null 2>&1; then
+        log_message "Error: $python_cmd not found. Exiting."
+        exit 1
+    fi
+
+    if ! "$python_cmd" -m venv --help > /dev/null 2>&1; then
+        log_message "Error: $python_cmd found, but venv module is not available. Exiting."
+        exit 1
+    fi
+
+    if ! "$python_cmd" -m pip --version > /dev/null 2>&1; then
+        log_message "Error: $python_cmd found, but pip is not installed. Exiting."
         exit 1
     fi
 }
@@ -565,9 +622,8 @@ add_psychopy_to_path() {
 }
 
 main() {
-    psychopy_version="2024.1.4"
+    psychopy_version="latest"
     python_version="3.10"
-    existing_python=false
     wxpython_version="4.2.2"
     build_python=false
     build_wx=false
@@ -593,9 +649,6 @@ main() {
                     echo "Error: Invalid Python version specified. Only versions 3.8, 3.9, or 3.10 are allowed."
                     exit 1
                 fi
-                ;;
-            --existing-python)
-                existing_python=true
                 ;;
             --wxpython-version=*)
                 wxpython_version="${arg#*=}"
@@ -670,12 +723,6 @@ main() {
     processor_structure=$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m)
     log_message "Info: Initiating PsychoPy(${psychopy_version}) installation on ${os_version} (${processor_structure})."
 
-    # Exit if --existing-python flag used but python not in path.
-    if [ "$existing_python" = true ] && ! command -v "python${python_version}" > /dev/null 2>&1; then
-        log_message "Error: Python${python_version} not in path use without --existing-python to install Python. Exiting."
-        exit 1
-    fi
-
     # Detect package manager
     pkg_manager=$(detect_package_manager)
 
@@ -719,16 +766,15 @@ main() {
         sudo_wrapper mkdir -p "${psychopy_dir}"
     fi
 
-    #Check if psychopy_dir is writeable else change ownership 
     [ -w "${psychopy_dir}" ] || sudo_wrapper chown "$USER" "${psychopy_dir}"
 
-    # Exit script if writing or changing directory to psychopy_dir is not possible
     if ! [ -w "${psychopy_dir}" ] || ! cd "${psychopy_dir}"; then
         log_message "Error: Failed to access or change directory to ${psychopy_dir}. Exiting."
         exit 1
     fi
     
-    if [ "$existing_python" = false ]; then
+    # Install python and create vnev
+    if [ "$build_python" = true ] || ! check_python_pkg_manager; then
         if [ "$build_python" = true ]; then
             build_python
         else
@@ -744,7 +790,7 @@ main() {
                 fi
             fi
         fi
-        # Check if the Python version was successfully installed in the custom directory
+
         if [ ! -x "/usr/local/psychopy_python/bin/python${python_version}" ]; then
             log_message "Error: python${python_version} not found in /usr/local/psychopy_python. Something went wrong while installing/building. Try --build=python and --verbose as arguments."
             exit 1
@@ -752,12 +798,17 @@ main() {
         export PATH=/usr/local/psychopy_python/bin:$PATH
         /usr/local/psychopy_python/bin/python"${python_version}" -m venv "${psychopy_dir}"
     else
+        log_message "Info: Python${python_version} can be installed via package manager. Installing ..."
+        install_dependencies python_with_venv
+        check_python_env "python${python_version}"
         python"${python_version}" -m venv "${psychopy_dir}"
     fi
 
+    # Activate venv
     log_message "Info: Succesfully created Python${python_version} venv in ${psychopy_dir} ... Activating."
     log source "${psychopy_dir}/bin/activate"
-    
+    check_python_env "python"
+
     # Upgrade pip and install required Python packages
     log_message "Info: Upgrading pip, distro, sip, six, psychtoolbox and attrdict ..."
     log pip install -U pip distro sip six psychtoolbox attrdict
@@ -794,7 +845,6 @@ main() {
         fi
     fi
 
-    # Check if wxPython was successfully installed
     if ! pip show wxPython &> /dev/null; then
         log_message "Error: wxPython is not installed. Something went wrong during the installation. Use --verbose and maybe --build=wxpython flags."
         exit 1
@@ -808,7 +858,6 @@ main() {
         log pip install psychopy=="${psychopy_version}"
     fi
 
-    # Check if PsychoPy was successfully installed
     if ! pip show psychopy &> /dev/null; then
         log_message "Error: PsychoPy is not installed successfully. Something went wrong during the installation. Use the --verbose flag."
         exit 1
