add sudo_mode force

diff --git a/psychopy_linux_installer b/psychopy_linux_installer
--- a/psychopy_linux_installer
+++ b/psychopy_linux_installer
@@ -99,8 +99,8 @@ for arg in "$@"; do
             ;;
         --sudo_mode=*)
             sudo_mode="${arg#*=}"
-            if [[ "$sudo_mode" != "ask" && "$sudo_mode" != "error" && "$sudo_mode" != "ok" ]]; then
-                echo "Error: Invalid value for --sudo_mode. Valid options are 'ask', 'error', or 'ok'."
+            if [[ "$sudo_mode" != "ask" && "$sudo_mode" != "auto" && "$sudo_mode" != "error"  && "$sudo_mode" != "force" ]]; then
+                echo "Error: Invalid value for --sudo_mode. Valid options are 'ask', 'auto', 'error' or 'force'."
                 exit 1
             fi
             ;;
@@ -135,62 +135,66 @@ log() {
 }
 
 sudo_wrapper() {
-    error_output=$("$@" 2>&1)
-    exit_code=$?
+    if [[ "$sudo_mode" == "force" ]]; then
+        log sudo "$@"
+    else
+        error_output=$("$@" 2>&1)
+        exit_code=$?
 
-    case "$sudo_mode" in
-        ask)
-            # Determine if the command is a package manager command
-            if [[ "$1" == "$pkg_manager" ]]; then
-                is_pkg_manager_command=true
-            else
-                is_pkg_manager_command=false
-            fi
-
-            # Handle package manager commands
-            if [ $exit_code -eq 126 ] || [ $exit_code -eq 100 ] || 
-               ([ $exit_code -ne 0 ] && log_message "$error_output" | grep -Eqi "permission denied|requires root|must be root|are not authorized|could not open|operation not permitted|cannot open|superuser privileges|has to be run with"); then
-                
-                if $is_pkg_manager_command && [[ "$pkg_manager_permission" == true ]]; then
-                    log sudo "$@"
+        case "$sudo_mode" in
+            ask)
+                # Determine if the command is a package manager command
+                if [[ "$1" == "$pkg_manager" ]]; then
+                    is_pkg_manager_command=true
                 else
-                    if $is_pkg_manager_command; then
-                        read -r -p "Command '$*' failed due to permission denied. Would you like to retry with sudo for this and all future $pkg_manager package manager commands? [y/N] " response
-                        if [[ "$response" =~ ^[Yy]$ ]]; then
-                            pkg_manager_permission=true
-                            log sudo "$@"
-                        else
-                            exit 1
-                        fi
+                    is_pkg_manager_command=false
+                fi
+
+                # Handle package manager commands
+                if [ $exit_code -eq 126 ] || [ $exit_code -eq 100 ] || 
+                ([ $exit_code -ne 0 ] && log_message "$error_output" | grep -Eqi "permission denied|requires root|must be root|are not authorized|could not open|operation not permitted|cannot open|superuser privileges|has to be run with"); then
+                    
+                    if $is_pkg_manager_command && [[ "$pkg_manager_permission" == true ]]; then
+                        log sudo "$@"
                     else
-                        read -r -p "Command '$*' failed due to permission denied. Would you like to retry with sudo? [y/N] " response
-                        if [[ "$response" =~ ^[Yy]$ ]]; then
-                            log sudo "$@"
+                        if $is_pkg_manager_command; then
+                            read -r -p "Command '$*' failed due to permission denied. Would you like to retry with sudo for this and all future $pkg_manager package manager commands? [y/N] " response
+                            if [[ "$response" =~ ^[Yy]$ ]]; then
+                                pkg_manager_permission=true
+                                log sudo "$@"
+                            else
+                                exit 1
+                            fi
                         else
-                            exit 1
+                            read -r -p "Command '$*' failed due to permission denied. Would you like to retry with sudo? [y/N] " response
+                            if [[ "$response" =~ ^[Yy]$ ]]; then
+                                log sudo "$@"
+                            else
+                                exit 1
+                            fi
                         fi
                     fi
                 fi
-            fi
-            ;;
-        error)
-            # Try without sudo, exit if permission denied
-            if [ $exit_code -eq 126 ] || [ $exit_code -eq 100 ] || 
-               ([ $exit_code -ne 0 ] && log_message "$error_output" | grep -Eqi "permission denied|requires root|must be root|are not authorized|could not open|operation not permitted|cannot open|superuser privileges|has to be run with"); then
-                log log_message "Error: Command '$*' failed due to permission denied. Sudo is required, but mode is set to 'error'."
-                exit 1  
-            fi
-            ;;
-        ok)
-            # Try without sudo, sudo if permission denied
-            if [ $exit_code -eq 126 ] || [ $exit_code -eq 100 ] || 
-               ([ $exit_code -ne 0 ] && log_message "$error_output" | grep -Eqi "permission denied|requires root|must be root|are not authorized|could not open|operation not permitted|cannot open|superuser privileges|has to be run with"); then
-                log log_message "Warning: Command '$*' failed due to permission denied. Using sudo..."
-                log sudo "$@" 
-            fi
-            ;;
-    esac
-}
+                ;;
+            auto)
+                # Try without sudo, sudo if permission denied
+                if [ $exit_code -eq 126 ] || [ $exit_code -eq 100 ] || 
+                ([ $exit_code -ne 0 ] && log_message "$error_output" | grep -Eqi "permission denied|requires root|must be root|are not authorized|could not open|operation not permitted|cannot open|superuser privileges|has to be run with"); then
+                    log log_message "Warning: Command '$*' failed due to permission denied. Using sudo..."
+                    log sudo "$@" 
+                fi
+                ;;
+            error)
+                # Try without sudo, exit if permission denied
+                if [ $exit_code -eq 126 ] || [ $exit_code -eq 100 ] || 
+                ([ $exit_code -ne 0 ] && log_message "$error_output" | grep -Eqi "permission denied|requires root|must be root|are not authorized|could not open|operation not permitted|cannot open|superuser privileges|has to be run with"); then
+                    log log_message "Error: Command '$*' failed due to permission denied. Sudo is required, but mode is set to 'error'."
+                    exit 1  
+                fi
+                ;;
+        esac
+    fi
+    }
 
 # Function to print log messages with timestamp
 log_message() {
