fix ubuntu-24.04 pavlovia NotImplementedError

diff --git a/psychopy_linux_installer b/psychopy_linux_installer
--- a/psychopy_linux_installer
+++ b/psychopy_linux_installer
@@ -153,7 +153,7 @@ sudo_wrapper() {
         local error_output=$2
         # Check various conditions that indicate sudo is needed
         [[ $exit_code -eq 126 ]] || [[ $exit_code -eq 100 ]] || 
-        ([[ $exit_code -ne 0 ]] && echo "$error_output" | grep -Eqi "permission denied|requires root|must be root|are not authorized|could not open|operation not permitted|cannot open|superuser privileges|has to be run with")
+        ([[ $exit_code -ne 0 ]] && echo "$error_output" | grep -Eqi "permission denied|requires root|must be root|are not authorized|could not open|operation not permitted|cannot open|superuser privileges|has to be run with|Error: must run as root")
     }
 
     # Function to handle sudo requests based on the sudo_mode
@@ -282,7 +282,19 @@ install_packages() {
     
     for package in "${packages[@]}"; do
         case $pkg_manager in
-            apt-get) sudo_wrapper apt-get install -y -qq "$package" || log_message "Package $package not found, skipping." ;;
+            apt-get)
+                if ! sudo_wrapper apt-get install -y -qq "$package"; then
+                    # libwebkit2gtk-4.0-dev is not available on ubuntu-24.04 and neccesary for Pavlovia
+                    if [ "$package" = "libwebkit2gtk-4.0-dev" ] && [ "$os_version" = "ubuntu-24.04" ]; then
+                        log_message "$package not found. Attempting to add focal repository and install."
+                        sudo_wrapper add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ focal main universe"
+                        sudo_wrapper apt-get install -y -qq "$package" || log_message "Failed to install $package from focal repository."
+                        sudo_wrapper add-apt-repository -y -r "deb http://archive.ubuntu.com/ubuntu/ focal main universe"
+                    else
+                        log_message "Warning: Package $package not found, skipping. (Pavlovia might not work)"
+                    fi
+                fi
+                ;;
             yum) sudo_wrapper yum install -y -q "$package" || log_message "Package $package not found, skipping." ;;
             dnf) sudo_wrapper dnf install -y -q "$package" || log_message "Package $package not found, skipping." ;;
             pacman) sudo_wrapper pacman -Sy --noconfirm "$package" || log_message "Package $package not found, skipping." ;;
