Add option to remove existing PsychoPy user settings during installation (#60)
* Add option to remove existing PsychoPy user settings during installation

* Uncouple requirements-file from other arguments; allow overrides and combinations

* Reorder desktop shortcut and PATH addition after user settings removal prompt

* Rename BACKUP_ADDITIONAL_PACKAGES to REQUIREMENTSFILE_PACKAGES

diff --git a/psychopy_linux_installer b/psychopy_linux_installer
--- a/psychopy_linux_installer
+++ b/psychopy_linux_installer
@@ -25,6 +25,7 @@ declare -A DEFAULT_OPTS=(
     [NON_INTERACTIVE]=false
     [FORCE_OVERWRITE]=false
     [VERBOSE]=false
+    [REMOVE_PSYCHOPY_SETTINGS]=false
 )
 
 # Displays usage information and available options.
@@ -47,6 +48,7 @@ show_help() {
             "  --non-interactive                             Run the installer without user interaction. Sets sudo-mode to auto if not set." \
             "  --disable-path                                Disable adding PsychoPy to system path." \
             "  --gui                                         Launches the installer in GUI mode, allowing you to set arguments interactively. Any arguments provided via the command line will be ignored while in GUI mode." \
+            "  --remove-psychopy-settings                    Remove existing PsychoPy user settings (${HOME}/.psychopy3). Retaining this folder can sometimes result in conflicts with plugins or non-default pip-installed packages." \
             "  -f, --force-overwrite                         Force overwrite of existing installation directory." \
             "  -v, --verbose                                 Enable verbose output for the terminal (logfile output is always verbose)." \
             "  -h, --help                                    Show this help message."
@@ -181,6 +183,9 @@ process_arguments() {
                 SUDO_MODE=auto
             fi
             ;;
+        --remove-psychopy-settings)
+            REMOVE_PSYCHOPY_SETTINGS=true
+            ;;
         -f | --force-overwrite)
             FORCE_OVERWRITE=true
             ;;
@@ -292,6 +297,7 @@ show_gui() {
         TRUE "Create desktop shortcuts" \
         FALSE "Run in non-interactive mode" \
         FALSE "Force overwrite of existing directory" \
+        FALSE "Remove PsychoPy user settings (${HOME}/.psychopy3)" \
         FALSE "Build Python from source" \
         FALSE "Build wxPython from source" \
         FALSE "Enable verbose output"); then
@@ -314,6 +320,10 @@ show_gui() {
 
     if [[ ${options} == *"Force overwrite of existing directory"* ]]; then
         FORCE_OVERWRITE=true
+    fi
+
+    if [[ ${options} == *"Remove PsychoPy user settings (${HOME}/.psychopy3)"* ]]; then
+        REMOVE_PSYCHOPY_SETTINGS=true
     fi
 
     if [[ ${options} == *"Build Python from source"* ]]; then
@@ -382,7 +392,7 @@ create_rerun_command() {
 
 # Reads and parses a requirements file, adjusting dependency versions as needed.
 parse_requirements_file() {
-    local file current_version operator package_name package_version pkg_lower version original_spec new_spec
+    local file current_version operator package_name package_version pkg_lower version original_spec new_spec req_python_version req_wxpython_version req_psychopy_version
     local -A package_versions
     local -A package_operators
     file="${1}"
@@ -414,7 +424,7 @@ parse_requirements_file() {
         fi
     done <"${file}"
 
-    BACKUP_ADDITIONAL_PACKAGES=$(for pkg in "${!package_versions[@]}"; do
+    REQUIREMENTSFILE_PACKAGES=$(for pkg in "${!package_versions[@]}"; do
         if [[ "${pkg}" != "wxpython" && "${pkg}" != "psychopy" && "${pkg}" != "winrt" && "${pkg}" != "pywin32" && "${pkg}" != "pypiwin32" && "${pkg}" != "pywinhook" ]]; then
             echo "${pkg}${package_operators[${pkg}]}${package_versions[${pkg}]}"
         else
@@ -424,9 +434,29 @@ parse_requirements_file() {
         fi
     done | tr '\n' ',' | sed 's/,$//')
 
-    PYTHON_VERSION=$(grep -i -E '^# Python version:' "${file}" | cut -d':' -f2 | xargs | cut -d'.' -f1,2 | tr -d '[:space:]' || true)
-    WXPYTHON_VERSION="${package_versions["wxpython"]:-}"
-    PSYCHOPY_VERSION="${package_versions["psychopy"]:-}"
+    # Extract versions from requirements file
+    req_python_version=$(grep -i -E '^# Python version:' "${file}" | cut -d':' -f2 | xargs | cut -d'.' -f1,2 | tr -d '[:space:]' || true)
+    req_wxpython_version="${package_versions["wxpython"]:-}"
+    req_psychopy_version="${package_versions["psychopy"]:-}"
+
+    # Set or warn for Python version, wxPython version, and PsychoPy version
+    if [ -n "${PYTHON_VERSION}" ] && [ -n "${req_python_version}" ] && [ "${PYTHON_VERSION}" != "${req_python_version}" ]; then
+        log_message "WARNING: Python version already set to '${PYTHON_VERSION}', but requirements file specifies '${req_python_version}'. Using '${PYTHON_VERSION}'."
+    elif [ -z "${PYTHON_VERSION}" ] && [ -n "${req_python_version}" ]; then
+        PYTHON_VERSION="${req_python_version}"
+    fi
+
+    if [ -n "${WXPYTHON_VERSION}" ] && [ -n "${req_wxpython_version}" ] && [ "${WXPYTHON_VERSION}" != "${req_wxpython_version}" ]; then
+        log_message "WARNING: wxPython version already set to '${WXPYTHON_VERSION}', but requirements file specifies '${req_wxpython_version}'. Using '${WXPYTHON_VERSION}'."
+    elif [ -z "${WXPYTHON_VERSION}" ] && [ -n "${req_wxpython_version}" ]; then
+        WXPYTHON_VERSION="${req_wxpython_version}"
+    fi
+
+    if [ -n "${PSYCHOPY_VERSION}" ] && [ -n "${req_psychopy_version}" ] && [ "${PSYCHOPY_VERSION}" != "${req_psychopy_version}" ]; then
+        log_message "WARNING: PsychoPy version already set to '${PSYCHOPY_VERSION}', but requirements file specifies '${req_psychopy_version}'. Using '${PSYCHOPY_VERSION}'."
+    elif [ -z "${PSYCHOPY_VERSION}" ] && [ -n "${req_psychopy_version}" ]; then
+        PSYCHOPY_VERSION="${req_psychopy_version}"
+    fi
 
     [[ -z "${PYTHON_VERSION}" ]] && log_message "WARNING: Python version not specified in the requirements file; using default: '${DEFAULT_OPTS[PYTHON_VERSION]}'."
     [[ -z "${WXPYTHON_VERSION}" ]] && log_message "WARNING: wxPython version not specified in the requirements file; using default: '${DEFAULT_OPTS[WXPYTHON_VERSION]}'."
@@ -434,7 +464,7 @@ parse_requirements_file() {
     if [ -z "${PSYCHOPY_VERSION}" ]; then
         log_message "ERROR: psychopy version not specified in requirements.txt." nolog
     else
-        BACKUP_ADDITIONAL_PACKAGES="${BACKUP_ADDITIONAL_PACKAGES:+${BACKUP_ADDITIONAL_PACKAGES},}psychopy==${PSYCHOPY_VERSION}"
+        REQUIREMENTSFILE_PACKAGES="${REQUIREMENTSFILE_PACKAGES:+${REQUIREMENTSFILE_PACKAGES},}psychopy==${PSYCHOPY_VERSION}"
     fi
 
     # Adjust Linux dependencies
@@ -444,8 +474,8 @@ parse_requirements_file() {
             version="${package_versions[${pkg_lower}]}"
             original_spec="${pkg_lower}${package_operators[${pkg_lower}]}${version}"
             new_spec="${pkg_lower}>=${version}"
-            if [[ "${BACKUP_ADDITIONAL_PACKAGES}" == *"${original_spec}"* ]]; then
-                BACKUP_ADDITIONAL_PACKAGES=${BACKUP_ADDITIONAL_PACKAGES//"${original_spec}"/"${new_spec}"}
+            if [[ "${REQUIREMENTSFILE_PACKAGES}" == *"${original_spec}"* ]]; then
+                REQUIREMENTSFILE_PACKAGES=${REQUIREMENTSFILE_PACKAGES//"${original_spec}"/"${new_spec}"}
                 log_message "WARNING: '${pkg}' from the requirements file was installed with a flexible version specification. '${original_spec}' may be platform-specific and was adjusted to '${new_spec}' for Linux compatibility. You may manually install the exact version in the PsychoPy venv." >&2
             fi
         fi
@@ -1444,7 +1474,7 @@ main() {
 
     if [ -n "${REQUIREMENTS_FILE}" ]; then
         log_message "INFO: Installing packages from requirements file ..."
-        transformed_packages=$(echo "${BACKUP_ADDITIONAL_PACKAGES}" | tr ',' '\n' | while read -r pkg; do
+        transformed_packages=$(echo "${REQUIREMENTSFILE_PACKAGES}" | tr ',' '\n' | while read -r pkg; do
             convert_psychopy_req_to_git_url "${pkg}"
         done)
 
@@ -1452,7 +1482,7 @@ main() {
             log_message "INFO: Packages from '${REQUIREMENTS_FILE}' installed successfully."
         else
             log_message "WARNING: Failed to install packages from '${REQUIREMENTS_FILE}'. Installing packages one by one ..."
-            IFS=',' read -ra PACKAGES <<<"${BACKUP_ADDITIONAL_PACKAGES}"
+            IFS=',' read -ra PACKAGES <<<"${REQUIREMENTSFILE_PACKAGES}"
             for package in "${PACKAGES[@]}"; do
                 log_message "INFO: Installing '${package}' ..."
                 transformed_pkg=$(convert_psychopy_req_to_git_url "${package}")
@@ -1479,21 +1509,21 @@ main() {
         if ! "${PYTHON_VENV_COMMAND}" -m pip show psychopy &>/dev/null; then
             log_message "ERROR: PsychoPy installation failed."
         fi
+    fi
 
-        # Install additional packages if specified
-        if [ -n "${ADDITIONAL_PACKAGES}" ]; then
-            log_message "INFO: Installing additional packages ..."
-            IFS=',' read -ra PACKAGES <<<"${ADDITIONAL_PACKAGES}"
-            for package in "${PACKAGES[@]}"; do
-                log_message "INFO: Installing '${package}' ..."
-                if log "${PYTHON_VENV_COMMAND}" -m pip install "${package}"; then
-                    installed_version=$("${PYTHON_VENV_COMMAND}" -m pip show "${package%%=*}" | grep Version | cut -d' ' -f2)
-                    log_message "INFO: '${package%%=*}' version '${installed_version}' installed successfully."
-                else
-                    log_message "WARNING: Failed to install '${package}'. Skipping."
-                fi
-            done
-        fi
+    # Install additional packages if specified
+    if [ -n "${ADDITIONAL_PACKAGES}" ]; then
+        log_message "INFO: Installing additional packages ..."
+        IFS=',' read -ra PACKAGES <<<"${ADDITIONAL_PACKAGES}"
+        for package in "${PACKAGES[@]}"; do
+            log_message "INFO: Installing '${package}' ..."
+            if log "${PYTHON_VENV_COMMAND}" -m pip install "${package}"; then
+                installed_version=$("${PYTHON_VENV_COMMAND}" -m pip show "${package%%=*}" | grep Version | cut -d' ' -f2)
+                log_message "INFO: '${package%%=*}' version '${installed_version}' installed successfully."
+            else
+                log_message "WARNING: Failed to install '${package}'. Skipping."
+            fi
+        done
     fi
 
     # Install numpy<2 if PsychoPy version is less than 2024.2.0
@@ -1512,6 +1542,26 @@ main() {
     sudo_wrapper usermod -a -G psychopy "${USER}"
     sudo_wrapper sh -c 'echo "@psychopy - nice -20\n@psychopy - rtprio 50\n@psychopy - memlock unlimited" > /etc/security/limits.d/99-psychopylimits.conf'
     log_message "NOTE: A system reboot is necessary to apply the security limits."
+
+    # Remove .psychopy3
+    if [ "${REMOVE_PSYCHOPY_SETTINGS}" = true ]; then
+        if [ -d "${HOME}/.psychopy3" ]; then
+            log_message "INFO: Removing existing '.psychopy3' directory."
+            sudo_wrapper rm -rf "${HOME}/.psychopy3"
+        fi
+    elif [ "${NON_INTERACTIVE}" = false ]; then
+        if [ -d "${HOME}/.psychopy3" ]; then
+            echo
+            read -r -p "Do you want to remove existing PsychoPy user settings in '${HOME}/.psychopy3'? (Retaining this folder can sometimes result in conflicts with plugins or non-default pip-installed packages.) [y/N] " response
+            echo
+            if [[ "${response}" =~ ^[Yy]$ ]]; then
+                log_message "INFO: Removing existing '.psychopy3' directory."
+                sudo_wrapper rm -rf "${HOME}/.psychopy3"
+            else
+                log_message "INFO: Skipped removing '.psychopy3' directory."
+            fi
+        fi
+    fi
 
     # Create desktop shortcut
     if [ "${DISABLE_SHORTCUT}" = false ]; then
