up

diff --git a/psychopy_linux_installer b/psychopy_linux_installer
--- a/psychopy_linux_installer
+++ b/psychopy_linux_installer
@@ -49,7 +49,7 @@ log_message() {
 
 # Function to parse requirements.txt
 parse_requirements_file() {
-    local file=$1
+    local file="$1"
     local -A package_versions
     local -A package_operators
 
@@ -118,8 +118,8 @@ sudo_wrapper() {
     local is_pkg_manager_command=false
 
     needs_sudo() {
-        local exit_code=$1
-        local error_output=$2
+        local exit_code="$1"
+        local error_output="$2"
 
         case $exit_code in
             0) return 1 ;;
@@ -285,7 +285,7 @@ install_packages() {
 
 # Function to install different types of dependencies
 install_dependencies() {
-    local dep_type=$1
+    local dep_type="$1"
     local dependencies=()
 
     case $pkg_manager in
@@ -378,28 +378,31 @@ version_greater_than() {
 
 # Function to get the all versions of a package from PyPI
 fetch_versions_from_pypi() {
-    package=$1
+    package="$1"
     curl -s "https://pypi.org/pypi/$package/json" | jq -r '.releases // {} | keys[]' | sort -Vr
 }
 
 # Function to get the latest version of a package from PyPI
 get_latest_pypi_version() {
-    local latest_version
-    local package_name=$1
-    latest_version=$(curl -s "https://pypi.org/pypi/${package_name}/json" | jq -r .info.version)
-    if [ -z "$latest_version" ]; then
+    local pkg="$1"
+    local var_name="$2"
+
+    local version
+    version=$(curl -s "https://pypi.org/pypi/$pkg/json" | jq -r '.info.version')
+    if [ -z "$version" ] || [ "$version" = "null" ]; then
         log_message "Error: Unable to fetch the latest version for package ${package_name}. Exiting."
         exit 1
     fi
-    echo "$latest_version"
+    declare -n result=$var_name
+    result="$version"
 }
 
 transform_package_spec() {
-    local package_spec=$1
+    local package_spec="$1"
 
     if [[ ! $package_spec =~ ^psychopy== ]] || [ "$PSYCHOPY_GIT_TAG" != "true" ]; then
         echo "$package_spec"
-        return
+        return 0
     fi
 
     local version=${package_spec#psychopy==}
@@ -408,8 +411,8 @@ transform_package_spec() {
 
 # Function to check if a specific version of a package exists on PyPI (extra rule for psychopy)
 check_pypi_for_version() {
-    local package=$1
-    local version=$2
+    local package="$1"
+    local version="$2"
     local GITHUB_API="https://api.github.com/repos/psychopy/psychopy/git/refs/tags"
     local PYPI_API="https://pypi.org/pypi"
 
@@ -426,8 +429,8 @@ check_pypi_for_version() {
         fi
     fi
 
-    log_message "Error: ${package} version ${version} not found on PyPI$([ "${package}" = "psychopy" ] && echo " or as git tag"). Exiting."
-    return 1
+    log_message "Error: ${package} version ${version} not found on PyPI. Exiting."
+    exit 1
 }
 
 # Function to check if python is in path and pip and venv are installed
@@ -991,7 +994,7 @@ main() {
 
     # Determine PsychoPy version to install
     if [ "$psychopy_version" == "latest" ]; then
-        psychopy_version=$(get_latest_pypi_version "psychopy")
+        get_latest_pypi_version "psychopy" psychopy_version
     elif [ "$psychopy_version" != "git" ]; then
         check_pypi_for_version psychopy "${psychopy_version}"
     fi
@@ -1077,7 +1080,7 @@ main() {
 
     # Determine wxPython version and install it
     if [ "$wxpython_version" = "latest" ]; then
-        wxpython_version=$(get_latest_pypi_version "wxPython")
+        get_latest_pypi_version "wxPython" wxpython_version
     elif [ "$wxpython_version" != "git" ]; then
         check_pypi_for_version wxpython "${wxpython_version}"
     fi
