Add zenity gui (#45)
* add support for requirements.txt

* add changelog

* update readme

* update docs

* allow empty additional packages

* ignore SC2181

* ignore SC2046

* rearrange packages

diff --git a/psychopy_linux_installer b/psychopy_linux_installer
--- a/psychopy_linux_installer
+++ b/psychopy_linux_installer
@@ -4,8 +4,8 @@
 #  Description:   This script installs PsychoPy with specified versions of
 #                 Python, wxPython, and optional packages.
 #  Author:        Lukas Wiertz
-#  Date:          2024-11-19
-#  Version:       1.3.2
+#  Date:          2025-01-17
+#  Version:       1.4.0
 #  License:       GNU General Public License v3.0
 # ==============================================================================
 
@@ -16,6 +16,7 @@ Options:
   --psychopy-version=VERSION                    Specify PsychoPy version (default: latest).
   --python-version=3.8|3.9|3.10                 Specify Python version (default: 3.10).
   --wxpython-version=VERSION                    Specify wxPython version (default: 4.2.2).
+  --requirements-file=FILE                      Specify a requirements.txt file to define dependencies.
   --build=[python|wxpython|both]                Build Python and/or wxPython from source instead of downloading.
   --install-dir=DIR                             Specify installation directory (default: "$HOME").
   --no-versioned-install-dir                    Install directly into install-dir without creating a versioned subdirectory. Requires --install-dir.
@@ -24,6 +25,7 @@ Options:
   --disable-shortcut                            Disable desktop shortcut creation.
   --non-interactive                             Run the installer without user interaction. Sets sudo-mode to auto if not set.
   --disable-path                                Disable adding psychopy to system path.
+  --gui                                         Launches the installer in GUI mode, allowing you to set arguments interactively. Any arguments provided via the command line will be ignored while in GUI mode.
   -f, --force                                   Force overwrite of existing installation directory.
   -v, --verbose                                 Enable verbose output.
   -h, --help                                    Show this help message.
@@ -42,6 +44,16 @@ log() {
 # Function to print log messages with timestamp
 log_message() {
     echo "$(date '+%Y-%m-%d %H:%M:%S') - $1"
+}
+
+# Function to parse requirements.txt
+parse_requirements_file() {
+    local file=$1
+
+    python_version=$(grep -E '^# Python version:' "$file" | cut -d':' -f2 | xargs | cut -d'.' -f1,2 | tr -d '[:space:]' || true)
+    wxpython_version=$(grep -E '^wxPython==' "$file" | awk -F'==' '{print $2}' | xargs | tr -d '[:space:]' || true)
+    psychopy_version=$(grep -E '^psychopy==' "$file" | awk -F'==' '{print $2}' | xargs | tr -d '[:space:]' || true)
+    additional_packages=$(grep -E -v '^(#|psychopy==|wxPython==)' "$file" | grep -E '.+==.+' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | tr '\n' ',' | sed 's/,$//' | tr -d '[:space:]' || true)
 }
 
 # Wrapper function to handle sudo requests and permissions dynamically
@@ -261,8 +273,8 @@ install_dependencies() {
         zypper)
             script_deps=(git curl jq)
             psychopy_deps=(gtk3-devel libxcb-xinerama0 libSDL2-devel libusb-1_0-devel portaudio-devel alsa-devel pulseaudio pulseaudio-utils libnotify4)
-            python_build_deps=(gcc libopenssl-devel zlib-devel sqlite3-devel libffi-devel bzip2-devel readline-devel xz-devel make)
-            wxpython_deps=(libpng16-devel gstreamer-plugins-base freeglut-devel libnotify-devel libSM-devel gtk2-devel gcc-c++ make glib2-devel)
+            python_build_deps=(gcc libopenssl-devel zlib-devel sqlite3-devel libffi-devel readline-devel xz-devel make)
+            wxpython_deps=(libpng16-devel gstreamer-plugins-base freeglut-devel libnotify-devel libSM-devel libjpeg-turbo gcc-c++ make glib2-devel)
             python_with_venv=(python3 python3-virtualenv python3-pip python3-devel)
             ;;
         *)
@@ -322,6 +334,12 @@ version_greater_than() {
     else
         return 1
     fi
+}
+
+# Function to get the all versions of a package from PyPI
+fetch_versions_from_pypi() {
+    package=$1
+    curl -s "https://pypi.org/pypi/$package/json" | jq -r '.releases | keys[]' | sort -Vr
 }
 
 # Function to get the latest version of a package from PyPI
@@ -664,24 +682,135 @@ add_psychopy_to_path() {
     fi
 }
 
-main() {
-    psychopy_version="latest"
-    python_version="3.10"
-    wxpython_version="4.2.2"
-    build_python=false
-    build_wx=false
-    install_dir="$HOME"
-    no_versioned_install_dir=false
+show_gui() {
+    # Optional Select requirements.txt
+    zenity --question --title="Use requirements.txt" \
+    --text="Do you want to use a requirements.txt file?\n\nIf you don't know what this is, choose 'No' to proceed with manual setup." \
+    --ok-label="Yes" --cancel-label="No"
+
+    if [ $? -eq 0 ]; then
+        requirements_file=$(zenity --file-selection --title="Select requirements.txt" --file-filter="requirements.txt | *.txt")
+        if [ $? -eq 0 ] && [ -n "$requirements_file" ]; then
+            use_requirements=true
+        else
+            exit 1
+        fi
+    else
+        use_requirements=false
+    fi
+
+    if [ "$use_requirements" = false ]; then
+        # Select PsychoPy version
+        psychopy_versions=$(fetch_versions_from_pypi psychopy)
+        first_psychopy_version=$(echo "$psychopy_versions" | head -1)
+        psychopy_version=$(zenity --list --title="PsychoPy Version" \
+            --text="Select the PsychoPy version:" \
+            --radiolist --column="Select" --column="Version" \
+            TRUE "$first_psychopy_version" $(echo "$psychopy_versions" | tail -n +2 | xargs -I{} printf "FALSE %s " {}) | tr -d '"')
+        psychopy_version=$(echo "$psychopy_version" | xargs)
+        if [ $? -ne 0 ] || [ -z "$psychopy_version" ]; then
+            exit 1
+        fi
+
+        # Select Python version
+        python_version=$(zenity --list --title="Python Version" \
+            --text="Select the Python version:" \
+            --radiolist --column="Select" --column="Version" \
+            TRUE "3.10" FALSE "3.9" FALSE "3.8")
+        python_version=$(echo "$python_version" | xargs)
+        if [ $? -ne 0 ] || [ -z "$python_version" ]; then
+            exit 1
+        fi
+
+        # Select wxPython version
+        wxpython_versions=$(fetch_versions_from_pypi wxPython)
+        default_wxpython_version="4.2.2"
+        wxpython_version=$(zenity --list --title="wxPython Version" \
+            --text="Select the wxPython version:" \
+            --radiolist --column="Select" --column="Version" \
+            TRUE "$default_wxpython_version" $(echo "$wxpython_versions" | grep -v "$default_wxpython_version" | xargs -I{} printf "FALSE %s " {}) | tr -d '"')
+        wxpython_version=$(echo "$wxpython_version" | xargs)
+        if [ $? -ne 0 ] || [ -z "$wxpython_version" ]; then
+            exit 1
+        fi
+
+        # Additional packages
+        additional_packages=$(zenity --entry --title="Additional Packages" \
+            --text="Specify additional pip packages to install (comma-separated).\nExample: psychopy-bids,another-package==1.2.3,package3\n\nLeave Empty for no additonal packages" \
+            --entry-text="")
+        additional_packages=$(echo "$additional_packages" | xargs)
+        if [ $? -ne 0 ]; then
+            exit 1
+        fi
+    fi
+
+    # Installation directory
+    install_dir=$(zenity --file-selection --directory --title="Select Installation Directory")
+    install_dir=$(echo "$install_dir" | xargs)
+    if [ $? -ne 0 ] || [ -z "$install_dir" ]; then
+        exit 1
+    fi
+
+    # Additional options with tooltips
+    options=$(zenity --list --checklist --title="Additional Options" \
+        --text="Select additional options:" \
+        --column="Select" --column="Option" \
+        TRUE "Create desktop shortcuts" \
+        TRUE "Add PsychoPy to system PATH" \
+        TRUE "Run in non-interactive mode" \
+        FALSE "Install without versioned subdirectory" \
+        FALSE "Force overwrite of existing directory" \
+        FALSE "Build Python from source" \
+        FALSE "Build wxPython from source" \
+        FALSE "Enable verbose output")
+    if [ $? -ne 0 ]; then
+        exit 1
+    fi
+
+    if [[ $options == *"Build Python from source"* ]]; then
+        build_python=true
+    fi
+    if [[ $options == *"Build wxPython from source"* ]]; then
+        build_wx=true
+    fi
+    if [[ $options == *"Create desktop shortcuts"* ]]; then
+        disable_shortcut=false
+    fi
+    if [[ $options == *"Add PsychoPy to system PATH"* ]]; then
+        disable_path=false
+    fi
+    if [[ $options == *"Install without versioned subdirectory"* ]]; then
+        no_versioned_install_dir=true
+    fi
+    if [[ $options == *"Force overwrite of existing directory"* ]]; then
+        force_overwrite=true
+    fi
+    if [[ $options == *"Enable verbose output"* ]]; then
+        verbose=true
+    fi
+    if [[ $options == *"Run in non-interactive mode"* ]]; then
+        non_interactive=true
+        sudo_mode=auto
+    fi
+    if [[ $non_interactive == false ]]; then
+        sudo_mode=$(zenity --list --title="Sudo Mode" \
+            --text="Select the desired sudo mode:\n\
+                ask: confirm each sudo usage.\n\
+                auto: auto-confirm sudo if required.\n\
+                error: exit if sudo is needed.\n\
+                continue: skip sudo commands, assuming prerequisites are met.\n\
+                force: use sudo for everything." \
+            --radiolist --column="Select" --column="Mode" \
+            TRUE "ask" FALSE "auto" FALSE "error" FALSE "continue" FALSE "force")
+        if [ $? -ne 0 ] || [ -z "$sudo_mode" ]; then
+            exit 1
+        fi
+    fi
+}
+
+process_arguments() {
     install_dir_set_by_user=false
-    additional_packages=""
-    sudo_mode="ask"
     sudo_mode_set=false
-    pkg_manager_permission=false
-    disable_shortcut=false
-    disable_path=false
-    non_interactive=false
-    force_overwrite=false
-    verbose=false
 
     for arg in "$@"; do
         case $arg in
@@ -697,6 +826,12 @@ main() {
                 ;;
             --wxpython-version=*)
                 wxpython_version="${arg#*=}"
+                ;;
+            --additional-packages=*)
+                additional_packages="${arg#*=}"
+                ;;
+            --requirements-file=*)
+                requirements_file="${arg#*=}"
                 ;;
             --build=*)
                 build_arg="${arg#*=}"
@@ -728,9 +863,6 @@ main() {
                     exit 1
                 fi
                 no_versioned_install_dir=true
-                ;;
-            --additional-packages=*)
-                additional_packages="${arg#*=}"
                 ;;
             --sudo-mode=*)
                 sudo_mode="${arg#*=}"
@@ -769,7 +901,49 @@ main() {
                 ;;
         esac
     done
+}
 
+main() {
+    use_gui=false
+    for arg in "$@"; do
+        if [[ "$arg" == "--gui" ]]; then
+            use_gui=true
+            break
+        fi
+    done
+
+    if $use_gui; then
+        if ! command -v zenity &> /dev/null; then
+            log_message "Error: zenity is not installed or not available in PATH. Cannot use GUI mode. Exiting."
+            exit 1
+        else
+            show_gui
+        fi
+    else
+        process_arguments "$@"
+    fi
+
+    if [ -n "$requirements_file" ]; then
+        log_message "Info: Parsing requirements file: $requirements_file..."
+        parse_requirements_file "$requirements_file"
+    fi
+
+    # Ensure defaults for unset variables
+    pkg_manager_permission=false
+    psychopy_version=${psychopy_version:-"latest"}
+    python_version=${python_version:-"3.10"}
+    wxpython_version=${wxpython_version:-"4.2.2"}
+    build_python=${build_python:-false}
+    build_wx=${build_wx:-false}
+    install_dir=${install_dir:-"$HOME"}
+    no_versioned_install_dir=${no_versioned_install_dir:-false}
+    additional_packages=${additional_packages:-""}
+    sudo_mode=${sudo_mode:-"ask"}
+    disable_shortcut=${disable_shortcut:-false}
+    disable_path=${disable_path:-false}
+    non_interactive=${non_interactive:-false}
+    force_overwrite=${force_overwrite:-false}
+    verbose=${verbose:-false}
 
     # Detect OS version and architecture
     os_version=$(detect_os_version | tr '[:upper:]' '[:lower:]')
