up

diff --git a/psychopy_linux_installer b/psychopy_linux_installer
--- a/psychopy_linux_installer
+++ b/psychopy_linux_installer
@@ -263,16 +263,15 @@ update_package_manager() {
         dnf) sudo_wrapper dnf makecache -q ;;
         pacman) log_message "Warning: Skipping 'pacman -Syu' to avoid unintended system upgrades. If you encounter a lot of 'package not found' errors, manually run 'sudo pacman -Syu' to update your package database, then rerun this script." ;;
         zypper) sudo_wrapper zypper refresh ;;
-        *) log_message "Error: No compatible package manager found."; exit 1 ;;
+        *) log_message "Error: No compatible package manager found. Exiting."; exit 1 ;;
     esac
 }
 
 # Function to check if a package is available
 filter_existing_packages() {
     local filtered_packages=()
-
     for package in "$@"; do
-        case $pkg_manager in
+        case "$pkg_manager" in
             apt-get)
                 if apt-cache show "$package" &>/dev/null; then
                     filtered_packages+=("$package")
@@ -281,7 +280,7 @@ filter_existing_packages() {
                 fi
                 ;;
             yum|dnf)
-                if yum list available "$package" &>/dev/null; then
+                if $pkg_manager info "$package" &>/dev/null; then
                     filtered_packages+=("$package")
                 else
                     log_message "Skipping unavailable package: $package"
@@ -302,12 +301,11 @@ filter_existing_packages() {
                 fi
                 ;;
             *)
-                log_message "Error: No compatible package manager found."
+                log_message "Error: No compatible package manager found. Exiting."
                 exit 1
                 ;;
         esac
     done
-
     echo "${filtered_packages[@]}"
 }
 
@@ -358,7 +356,7 @@ install_dependencies() {
     case $pkg_manager in
         apt-get)
             script_deps=(git curl jq)
-            psychopy_deps=(libgtk-3-dev libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libxcb-xinerama0 libegl1-mesa-dev libsdl2-dev libglu1-mesa-dev libusb-1.0-0-dev portaudio19-dev libasound2-dev libxcb-cursor0 libxkbcommon-x11-0 pulseaudio pulseaudio-utils libnotify4 libglib2.0-dev)
+            psychopy_deps=(libgtk-3-dev libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libxcb-xinerama0 libegl1-mesa-dev libsdl2-dev libglu1-mesa-dev libusb-1.0-0-dev portaudio19-dev libasound2-dev libxcb-cursor0 libxkbcommon-x11-0 pulseaudio-utils libnotify4 libglib2.0-dev)
             python_build_deps=(build-essential libssl-dev zlib1g-dev libsqlite3-dev libffi-dev libbz2-dev libreadline-dev xz-utils make)
             wxpython_deps=(libjpeg-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x freeglut3-dev libpng-dev libtiff-dev libnotify-dev libsm-dev libgtk2.0-dev g++ make)
             python_with_venv=(python3 python3-venv python3-pip python3-dev)
