fix order, check for python in path

diff --git a/psychopy_linux_installer b/psychopy_linux_installer
--- a/psychopy_linux_installer
+++ b/psychopy_linux_installer
@@ -4,8 +4,8 @@
 #  Description:   This script installs PsychoPy with specified versions of
 #                 Python, wxPython, and optional packages.
 #  Author:        Lukas Wiertz
-#  Date:          2024-10-25
-#  Version:       1.2.0
+#  Date:          2024-10-27
+#  Version:       1.2.1
 #  License:       GNU General Public License v3.0
 # ==============================================================================
 
@@ -13,17 +13,17 @@ show_help() {
     cat << EOF
 Usage: ./psychopy_linux_installer [options]
 Options:
-  --python-version=3.8|3.9|3.10                 Specify Python version (default: 3.10).
   --psychopy-version=VERSION                    Specify PsychoPy version (default: 2024.1.4).
+  --python-version=3.8|3.9|3.10                 Specify Python version (default: 3.10).
+  --use-system-python                           Use the system-installed Python instead of installing a new version. Requires Python (version 3.*), pip, and venv to be pre-installed and accessible in the system path.
   --wxpython-version=VERSION                    Specify wxPython version (default: 4.2.2).
+  --build=[python|wxpython|both]                Build Python and/or wxPython from source instead of downloading.
   --install-dir=DIR                             Specify installation directory (default: "$HOME").
   --no-versioned-install-dir                    Install directly into install-dir without creating a versioned subdirectory. Requires --install-dir.
   --additional-packages=PACKAGES                Specify additional pip packages to install. Format: package1==version,package2. No version is latest.
-  --build=[python|wxpython|both]                Build Python and/or wxPython from source instead of downloading.
   --sudo-mode=[ask|auto|error|continue|force]   Control sudo usage. ask: confirm, auto: auto-confirm, error: exit if sudo needed, continue: continue without sudo, force: use sudo directly.
   --disable-shortcut                            Disable desktop shortcut creation.
   --disable-path                                Disable adding psychopy to system path.
-  --use-system-python                           Use the system-installed Python instead of installing a new version. Requires Python (version 3.*), pip, and venv to be pre-installed and accessible in the system path.
   -f, --force                                   Force overwrite of existing installation directory.
   -v, --verbose                                 Enable verbose output.
   -h, --help                                    Show this help message.
@@ -569,25 +569,28 @@ add_psychopy_to_path() {
 }
 
 main() {
-    python_version="3.10"
     psychopy_version="2024.1.4"
+    python_version="3.10"
+    use_system_python=false
     wxpython_version="4.2.2"
+    build_python=false
+    build_wx=false
     install_dir="$HOME"
     no_versioned_install_dir=false
     install_dir_set_by_user=false
     additional_packages=""
-    build_python=false
-    build_wx=false
     sudo_mode="ask"
     pkg_manager_permission=false
-    force_overwrite=false
-    verbose=false
     disable_shortcut=false
     disable_path=false
-    use_system_python=false
+    force_overwrite=false
+    verbose=false
 
     for arg in "$@"; do
         case $arg in
+            --psychopy-version=*)
+                psychopy_version="${arg#*=}"
+                ;;
             --python-version=*)
                 python_version="${arg#*=}"
                 if [[ ! $python_version =~ ^3\.(8|9|10)$ ]]; then
@@ -595,25 +598,11 @@ main() {
                     exit 1
                 fi
                 ;;
-            --psychopy-version=*)
-                psychopy_version="${arg#*=}"
+            --use-system-python)
+                use_system_python=true
                 ;;
             --wxpython-version=*)
                 wxpython_version="${arg#*=}"
-                ;;
-            --install-dir=*)
-                install_dir="${arg#*=}"
-                install_dir_set_by_user=true
-                ;;
-            --no-versioned-install-dir)
-                if [ "$install_dir_set_by_user" = false ]; then
-                    echo "Error: --no-versioned-install-dir cannot be used without setting --install_dir."
-                    exit 1
-                fi
-                no_versioned_install_dir=true
-                ;;
-            --additional-packages=*)
-                additional_packages="${arg#*=}"
                 ;;
             --build=*)
                 build_arg="${arg#*=}"
@@ -635,6 +624,20 @@ main() {
                         ;;
                 esac
                 ;;
+            --install-dir=*)
+                install_dir="${arg#*=}"
+                install_dir_set_by_user=true
+                ;;
+            --no-versioned-install-dir)
+                if [ "$install_dir_set_by_user" = false ]; then
+                    echo "Error: --no-versioned-install-dir cannot be used without setting --install_dir."
+                    exit 1
+                fi
+                no_versioned_install_dir=true
+                ;;
+            --additional-packages=*)
+                additional_packages="${arg#*=}"
+                ;;
             --sudo-mode=*)
                 sudo_mode="${arg#*=}"
                 if [[ "$sudo_mode" != "ask" && "$sudo_mode" != "continue" && "$sudo_mode" != "auto" && "$sudo_mode" != "error"  && "$sudo_mode" != "force" ]]; then
@@ -647,9 +650,6 @@ main() {
                 ;;
             --disable-path)
                 disable_path=true
-                ;;
-            --use-system-python)
-                use_system_python=true
                 ;;
             -f|--force)
                 force_overwrite=true
@@ -673,6 +673,12 @@ main() {
     os_version=$(detect_os_version | tr '[:upper:]' '[:lower:]')
     processor_structure=$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m)
     log_message "Info: Initiating PsychoPy(${psychopy_version}) installation on ${os_version} (${processor_structure})."
+
+    # Exit if --use-system-python flag used but python not in path.
+    if [ "$use_system_python" = true ] && ! command -v "python${python_version}" > /dev/null 2>&1; then
+        log_message "Error: Python${python_version} not in path use without --use-system-python to install Python. Exiting."
+        exit 1
+    fi
 
     # Detect package manager
     pkg_manager=$(detect_package_manager)
@@ -725,7 +731,7 @@ main() {
         log_message "Error: Failed to access or change directory to ${psychopy_dir}. Exiting."
         exit 1
     fi
-
+    
     if [ "$use_system_python" = false ]; then
         if [ "$build_python" = true ]; then
             build_python
@@ -753,6 +759,7 @@ main() {
         python"${python_version}" -m venv "${psychopy_dir}"
     fi
 
+    log_message "Info: Succesfully created Python${python_version} venv in ${psychopy_dir} ... Activating."
     log source "${psychopy_dir}/bin/activate"
     
     # Upgrade pip and install required Python packages
@@ -761,7 +768,7 @@ main() {
 
     # Install numpy<2 if PsychoPy version is less than 2024.2.0
     if version_greater_than "2024.2.0" "$psychopy_version"; then
-        log_message "Info:PsychoPy version < 2024.2.0, installing numpy<2"
+        log_message "Info: PsychoPy version < 2024.2.0, installing numpy<2"
         log pip install "numpy<2"
     fi
 
