fix --find-links for wxpython; before it did never work because it needs the OS

diff --git a/psychopy_linux_installer b/psychopy_linux_installer
--- a/psychopy_linux_installer
+++ b/psychopy_linux_installer
@@ -520,7 +520,7 @@ sudo_wrapper() {
                 log_message "Warning: Command '${command[*]}' failed with: '${error_output}'. Continuing without sudo..."
                 ;;
             error)
-                log_message "Error: Command '${command[*]}' failed with '${error_output}'. Sudo is required, but mode is set to 'error'."
+                log_message "Error: Command '${command[*]}' failed with '${error_output}'. Sudo is required, but mode is set to 'error'. Exiting."
                 exit 1
                 ;;
         esac
@@ -580,24 +580,46 @@ check_script_update() {
 
 # Determines the operating system and its version.
 detect_os_version() {
+    OS_VERSION=""
+    OS_VERSION_LINK=""
+
     local major_version version ID VERSION_ID
     if [ -f /etc/os-release ]; then
         . /etc/os-release
         if [ -n "$ID" ] && [ -n "$VERSION_ID" ]; then
+            ID=$(echo "$ID" | tr '[:upper:]' '[:lower:]')
+            VERSION_ID=$(echo "$VERSION_ID" | tr '[:upper:]' '[:lower:]')
             major_version=$(echo "$VERSION_ID" | cut -d. -f1)
-            echo "$ID-$major_version"
+
+            OS_VERSION="${ID}-${major_version}"
+
+            if [ "$ID" = "ubuntu" ]; then
+                OS_VERSION_LINK="${ID}-${VERSION_ID}"
+            else
+                OS_VERSION_LINK="$OS_VERSION"
+            fi
             return
         fi
     fi
 
     if command -v lsb_release > /dev/null 2>&1; then
-        version=$(lsb_release -sr | cut -d. -f1)
-        echo "$(lsb_release -si)-$version"
+        ID=$(lsb_release -si | tr '[:upper:]' '[:lower:]')
+        version=$(lsb_release -sr | tr '[:upper:]' '[:lower:]')
+        major_version=$(echo "$version" | cut -d. -f1)
+
+        OS_VERSION="${ID}-${major_version}"
+
+        if [ "$ID" = "ubuntu" ]; then
+            OS_VERSION_LINK="${ID}-${version}"
+        else
+            OS_VERSION_LINK="$OS_VERSION"
+        fi
         return
     fi
 
     log_message "Warning: Unable to detect OS version."
-    echo "unknown"
+    OS_VERSION="unknown"
+    OS_VERSION_LINK="unknown"
     return
 }
 
@@ -656,7 +678,7 @@ install_packages() {
             dnf)     sudo_wrapper dnf install -y -q   "${available_packages[@]}" ;;
             pacman)  sudo_wrapper pacman -S --needed --noconfirm "${available_packages[@]}" ;;
             zypper)  sudo_wrapper zypper install -y   "${available_packages[@]}" ;;
-            *)       log_message "Error: No compatible package manager found." ; exit 1 ;;
+            *)       log_message "Error: No compatible package manager found. Exiting." ; exit 1 ;;
         esac
     }; then
         return 0
@@ -672,7 +694,7 @@ install_packages() {
             dnf) sudo_wrapper dnf install -y -q "$package" || log_message "Warning: Package $package not found, skipping." ;;
             pacman) sudo_wrapper pacman -S --needed --noconfirm "$package" || log_message "Warning: Package $package not found, skipping." ;;
             zypper) sudo_wrapper zypper install -y "$package" || log_message "Warning: Package $package not found, skipping." ;;
-            *) log_message "Error: No compatible package manager found."; exit 1 ;;
+            *) log_message "Error: No compatible package manager found. Exiting."; exit 1 ;;
         esac
     done
 }
@@ -718,7 +740,7 @@ install_dependencies() {
             python_with_venv=(python3 python3-devel python3-pip python3-virtualenv)
             ;;
         *)
-            log_message "Error: No compatible package manager found."; exit 1
+            log_message "Error: No compatible package manager found. Exiting."; exit 1
             ;;
     esac
 
@@ -729,7 +751,7 @@ install_dependencies() {
         fonts) dependencies=("${fonts[@]}") ;;
         wxpython_deps) dependencies=("${wxpython_deps[@]}") ;;
         python_with_venv) dependencies=("${python_with_venv[@]}") ;;
-        *) log_message "Error: Invalid dependency type specified."; exit 1 ;;
+        *) log_message "Error: Invalid dependency type specified. Exiting."; exit 1 ;;
     esac
 
     install_packages "${dependencies[@]}"
@@ -799,7 +821,7 @@ check_python_in_package_manager() {
             available_version=$(zypper info python3 2> /dev/null | grep -m 1 Version | awk '{print $3}' | cut -d'.' -f1,2)
             ;;
         *)
-            log_message "Error: No compatible package manager found."; exit 1
+            log_message "Error: No compatible package manager found. Exiting."; exit 1
             ;;
     esac
 
@@ -911,22 +933,22 @@ build_python() {
     temp_dir="Python-${latest_patch_version}_temp"
 
     if ! log curl -L -o "${temp_file}" "${official_url}"; then
-        log_message "Error: Failed to download Python source from ${official_url}."
+        log_message "Error: Failed to download Python source from ${official_url}. Exiting."
         exit 1
     fi
 
-    mkdir -p "${temp_dir}" || { log_message "Error: Failed to create temp directory."; exit 1; }
+    mkdir -p "${temp_dir}" || { log_message "Error: Failed to create temp directory. Exiting."; exit 1; }
 
     if ! tar -xf "${temp_file}" -C "${temp_dir}"; then
-        log_message "Error: Failed to extract ${temp_file}."
+        log_message "Error: Failed to extract ${temp_file}.  Exiting."
         exit 1
     fi
 
-    cd "${temp_dir}/Python-${latest_patch_version}" || { log_message "Error: Failed to change directory."; exit 1; }
+    cd "${temp_dir}/Python-${latest_patch_version}" || { log_message "Error: Failed to change directory.  Exiting."; exit 1; }
     log ./configure --enable-optimizations --with-ensurepip=install --prefix=/usr/local/psychopy_python
     log make -j "$(nproc)"
     sudo_wrapper make altinstall
-    cd "${PSYCHOPY_DIR}" || { log_message "Error: Failed to return to psychopy directory."; exit 1; }
+    cd "${PSYCHOPY_DIR}" || { log_message "Error: Failed to return to psychopy directory. Exiting."; exit 1; }
 
     sudo_wrapper rm -rf "${temp_dir}" "${temp_file}"
     return 0
@@ -1002,7 +1024,7 @@ build_wxpython() {
     if pip install --no-binary=wxpython --no-cache-dir --force-reinstall "wxpython==$WXPYTHON_VERSION"; then
         log_message "Info: Successfully built wxPython from source."
     else
-        log_message "Error: Building wxPython from source failed."
+        log_message "Error: Building wxPython from source failed. Exiting."
         exit 1
     fi
 }
@@ -1222,8 +1244,8 @@ main() {
         echo
     fi
 
-    # Detect OS version and architecture
-    OS_VERSION=$(detect_os_version | tr '[:upper:]' '[:lower:]')
+    # Detect OS version, architecture and script version
+    detect_os_version
     PROCESSOR_STRUCTURE=$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m)
     SCRIPT_VERSION=$(grep -m 1 'Version:' "$0" | sed 's/[^0-9.]//g')
     log_message "Info: Initiating PsychoPy(${PSYCHOPY_VERSION}) installation using psychopy_linux_installer v${SCRIPT_VERSION} on ${OS_VERSION} (${PROCESSOR_STRUCTURE})."
@@ -1313,7 +1335,7 @@ main() {
         fi
 
         if [ ! -x "/usr/local/psychopy_python/bin/python${PYTHON_VERSION}" ]; then
-            log_message "Error: python${PYTHON_VERSION} not found in /usr/local/psychopy_python. Something went wrong while installing/building. Try --build=python and --verbose as arguments."
+            log_message "Error: python${PYTHON_VERSION} not found in /usr/local/psychopy_python. Something went wrong while installing/building. Try --build=python and --verbose as arguments. Exiting."
             exit 1
         fi
         export PATH=/usr/local/psychopy_python/bin:$PATH
@@ -1352,19 +1374,22 @@ main() {
         install_dependencies wxpython_deps
         log_message "Info: Building wxPython from git. This might take a while ..."
         log pip install git+https://github.com/wxWidgets/Phoenix
-
     elif [ "$BUILD_WX" = true ]; then
         build_wxpython
-
     else
-        log pip install --only-binary=:all: --find-links /usr/local/psychopy_python/wx_wheels/ "wxpython==$WXPYTHON_VERSION" || \
-        log pip install --only-binary=:all: --find-links https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ "wxPython==$WXPYTHON_VERSION" || \
-        install_wxpython_from_github || \
-        build_wxpython
+        if log pip install --only-binary=:all: --find-links /usr/local/psychopy_python/wx_wheels/ "wxpython==$WXPYTHON_VERSION"; then
+            log_message "Info: Successfully installed wxPython $WXPYTHON_VERSION from local wheel."
+        elif log pip install --only-binary=:all: --find-links https://extras.wxpython.org/wxPython4/extras/linux/gtk3/$OS_VERSION_LINK/ "wxPython==$WXPYTHON_VERSION"; then
+            log_message "Info: Successfully installed wxPython $WXPYTHON_VERSION from extras.wxpython.org."
+        elif install_wxpython_from_github; then
+            :
+        else build_wxpython
+            :
+        fi
     fi
 
     if ! pip show wxPython &> /dev/null; then
-        log_message "Error: wxPython is not installed. Something went wrong during the installation. Try --build=wxpython and --verbose as arguments."
+        log_message "Error: wxPython is not installed. Something went wrong during the installation. Try --build=wxpython and --verbose as arguments. Exiting."
         exit 1
     fi
 
@@ -1403,7 +1428,7 @@ main() {
         fi
 
         if ! pip show psychopy &> /dev/null; then
-            log_message "Error: PsychoPy is not installed successfully. Something went wrong during the installation. Use the --verbose flag."
+            log_message "Error: PsychoPy is not installed successfully. Something went wrong during the installation. Use the --verbose flag. Exiting."
             exit 1
         fi
 
