check test output

diff --git a/.github/workflows/actions.yaml b/.github/workflows/actions.yaml
--- a/.github/workflows/actions.yaml
+++ b/.github/workflows/actions.yaml
@@ -28,7 +28,7 @@ jobs:
     strategy:
       matrix:
         os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
-        python_version: ['3.8.16', '3.9.19', '3.10.14',]
+        python_version: ['3.8.16', '3.9.19', '3.10.14']
         psychopy_version: ['latest','git', '2023.2.3', '2024.1.3']
         bids_version: ['','git', '2023.2.0']
       fail-fast: false
@@ -90,9 +90,15 @@ jobs:
       id: psychopy-test
       continue-on-error: true
       run: |
-        ${{ env.PYTHON_VENV }} ./.github/workflows/psychopy_test.py
-
-    - name: Verify BIDS installation
+        ${{ env.PYTHON_VENV }} ./.github/workflows/psychopy_test.py 2>&1 | tee psychopy_test.log
+        cat psychopy_test.log
+        set -e
+        if ! tail -n 1 psychopy_test.log | grep -qE "Trial 3: Elapsed time .* seconds"; then
+          echo "::error::PsychoPy test output verification failed"
+          exit 1
+        fi
+    
+        - name: Verify BIDS installation
       if: matrix.bids_version != ''
       id: verify-bids
       continue-on-error: true
@@ -100,11 +106,21 @@ jobs:
         ${{ env.PYTHON_VENV }} ./.github/workflows/bids_test_simple.py 2>&1 | tee output_simple.log
         echo "Output of bids_test_simple.py:"
         cat output_simple.log
-        
+        set -e
+        if ! tail -n 1 output_simple.log | grep -qE "└─participants.json"; then
+          echo "::error::BIDS test output verification failed"
+          exit 1
+        fi
+        echo "BIDS test output verification passed"
         ${{ env.PYTHON_VENV }} ./.github/workflows/bids_test_exp_handler.py 2>&1 | tee output_exp_handler.log
         echo "Output of bids_test_exp_handler.py:"
         cat output_exp_handler.log
-    
+        set -e
+        if ! tail -n 1 output_exp_handler.log | grep -qE "└─participants.json"; then
+          echo "::error::BIDS test output verification failed"
+          exit 1
+        fi
+        echo "BIDS test output verification passed"
     - name: Record result
       run: |
         STATUS="❌"
