fix pavlovia NotImplementedError for wheelfile

diff --git a/.github/workflows/build_python_wxpython.yaml b/.github/workflows/build_python_wxpython.yaml
--- a/.github/workflows/build_python_wxpython.yaml
+++ b/.github/workflows/build_python_wxpython.yaml
@@ -106,6 +106,17 @@ jobs:
             for pkg in "${packages[@]}"; do
               sudo apt-get install -y "$pkg" || true
             done
+            # Check if libwebkit2gtk-4.0-dev is installed (fixes ubuntu-24.04)
+            if [ "${{ matrix.os }}" = "ubuntu-24.04" ]; then
+              echo "Ubuntu 24.04 detected. Checking for libwebkit2gtk-4.0-dev..."
+              if ! dpkg -s libwebkit2gtk-4.0-dev &> /dev/null; then
+                echo "libwebkit2gtk-4.0-dev not found. Adding focal repository and installing..."
+                sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ focal main universe"
+                sudo apt-get update
+                sudo apt-get install -y libwebkit2gtk-4.0-dev
+              else
+                echo "libwebkit2gtk-4.0-dev is already installed."
+              fi
           elif command -v pacman > /dev/null; then
             sudo pacman -Syu --noconfirm || true
             packages=(
