use psychopy version for test

diff --git a/.github/workflows/reusable_test.yaml b/.github/workflows/reusable_test.yaml
--- a/.github/workflows/reusable_test.yaml
+++ b/.github/workflows/reusable_test.yaml
@@ -43,18 +43,16 @@ jobs:
 
       - name: Verify PsychoPy installation and version
         run: |
-          if ! /tmp_dir/psychopy/bin/psychopy -h &> /dev/null; then
-            echo "PsychoPy help command failed"
-            exit 1
-          fi
+          if [ "$PSYCHOPY_VERSION" = "latest" ]; then
+            PSYCHOPY_VERSION=$(curl -s "https://pypi.org/pypi/psychopy/json" | jq -r .info.version)
           
-          if ! /tmp_dir/psychopy/bin/psychopy -v | grep -qE "PsychoPy3, version [0-9]+\.[0-9]+\.[0-9]+"; then
-            echo "PsychoPy version check failed"
-            exit 1
+          if ! /tmp_dir/psychopy/bin/psychopy -v | grep -qE "PsychoPy3, version $PSYCHOPY_VERSION"; then
+              echo "PsychoPy version check failed. Expected version: $PSYCHOPY_VERSION"
+              exit 1
           else
-            /tmp_dir/psychopy/bin/psychopy -v
+              /tmp_dir/psychopy/bin/psychopy -v
           fi
-
+      
       - name: Run basic PsychoPy test
         if: ${{ !inputs.quick-mode }}
         run: |
