split bids_test

diff --git a/.github/workflows/test_installer.yaml b/.github/workflows/test_installer.yaml
--- a/.github/workflows/test_installer.yaml
+++ b/.github/workflows/test_installer.yaml
@@ -106,7 +106,7 @@ jobs:
             exit 1
           fi
 
-      - name: Verify BIDS installation
+      - name: Verify BIDS installation simple
         if: matrix.bids_version != ''
         id: verify-bids
         continue-on-error: true
@@ -118,24 +118,28 @@ jobs:
             exit 1
           fi
 
-          ${{ env.PYTHON_VENV }} $GITHUB_WORKSPACE/.github/workflows/bids_test_exp_handler.py 2>&1 | tee /tmp_dir/output_exp_handler.log
-          set -e
-          if ! tail -n 1 /tmp_dir/output_exp_handler.log | grep -qE "└─participants.json"; then
-            echo "::error::BIDS test output verification failed"
-            exit 1
-          fi
+      - name: Verify BIDS installation exp_handler
+        if: matrix.bids_version != ''
+        id: verify-bids-handler
+        run: |
+          continue-on-error: true
+            ${{ env.PYTHON_VENV }} $GITHUB_WORKSPACE/.github/workflows/bids_test_exp_handler.py 2>&1 | tee /tmp_dir/output_exp_handler.log
+            set -e
+            if ! tail -n 1 /tmp_dir/output_exp_handler.log | grep -qE "└─participants.json"; then
+              echo "::error::BIDS test output verification failed"
+              exit 1
+            fi
 
       - name: Determine versions
         id: determine-versions
         run: |
-          # Determine PsychoPy version
           if [ "${{ matrix.psychopy_version }}" == "git" ]; then
             latest_version=$(curl -s https://api.github.com/repos/psychopy/psychopy/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
             PSYCHOPY_VERSION_CLEAN=$(echo "${latest_version}" | tr -d ',;')
           else
             PSYCHOPY_VERSION_CLEAN=$(echo "${{ matrix.psychopy_version }}" | tr -d ',;')
           fi
-      
+
           # Determine BIDS version from GitLab if "git"
           if [ "${{ matrix.bids_version }}" == "git" ]; then
             latest_bids_version=$(curl -s https://gitlab.com/api/v4/projects/psygraz%2Fpsychopy-bids/releases | jq -r '.[0].tag_name')
@@ -143,17 +147,15 @@ jobs:
           else
             BIDS_VERSION_CLEAN=$(echo "${{ matrix.bids_version }}" | tr -d ',;')
           fi
-      
+
           # Set environment variables and outputs
           echo "PSYCHOPY_VERSION_CLEAN=$PSYCHOPY_VERSION_CLEAN" >> $GITHUB_ENV
           echo "BIDS_VERSION_CLEAN=$BIDS_VERSION_CLEAN" >> $GITHUB_ENV
-          echo "::set-output name=psychopy_version_clean::$PSYCHOPY_VERSION_CLEAN"
-          echo "::set-output name=bids_version_clean::$BIDS_VERSION_CLEAN"
         
       - name: Record result
         run: |
           STATUS="❌"
-          if [[ "${{ steps.run-installer.outcome }}" == "success" && "${{ steps.extract-command.outcome }}" == "success" && "${{ steps.verify-help.outcome }}" == "success" && "${{ steps.verify-version.outcome }}" == "success" && "${{ steps.psychopy-test.outcome }}" == "success" && ( -z "${{ matrix.bids_version }}" || "${{ steps.verify-bids.outcome }}" == "success" ) ]]; then
+          if [[ "${{ steps.run-installer.outcome }}" == "success" && "${{ steps.extract-command.outcome }}" == "success" && "${{ steps.verify-help.outcome }}" == "success" && "${{ steps.verify-version.outcome }}" == "success" && "${{ steps.psychopy-test.outcome }}" == "success" && ( -z "${{ matrix.bids_version }}" || "${{ steps.verify-bids.outcome }}" == "success" )  && ( -z "${{ matrix.bids_version }}" || "${{ steps.verify-bids-handler.outcome }}" == "success" )]]; then
             STATUS="✅"
           fi
       
