Action refactor (#18)
* test action-refactor

* fix build result

* check psychopy -h only for fail

* Update build results

* Update installation results

* fixes

* adapt to new --additional-packages argument

* forgot seedir for runners

---------

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

diff --git a/.github/workflows/test_installer.yaml b/.github/workflows/test_installer.yaml
--- a/.github/workflows/test_installer.yaml
+++ b/.github/workflows/test_installer.yaml
@@ -4,27 +4,24 @@ on:
   push:
     branches:
       - main
-    paths-ignore:
-      - 'README.md'
-      - 'LICENSE'
-      - '.github/workflows/build_python_wxpython.yaml'
-      - '.github/workflows/test_build.yaml'
+      - action-refactor
+    paths:
+      - psychopy_linux_installer
+      - .github/workflows/test_installer.yaml
+  workflow_dispatch:
 
 jobs:
   syntax-check:
-    runs-on: [self-hosted, ubuntu-24.04]
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Install ShellCheck
-        run: sudo apt-get install -y shellcheck
-
-      - name: Check Bash Syntax
-        run: bash -n $GITHUB_WORKSPACE/psychopy_linux_installer
-
       - name: Run ShellCheck
-        run: shellcheck -e SC1017 -e SC1091 $GITHUB_WORKSPACE/psychopy_linux_installer
+        run: |
+          sudo apt-get install -y shellcheck
+          bash -n $GITHUB_WORKSPACE/psychopy_linux_installer
+          shellcheck -e SC1017 -e SC1091 $GITHUB_WORKSPACE/psychopy_linux_installer
 
   run-installer:
     needs: syntax-check
@@ -36,96 +33,53 @@ jobs:
         psychopy_version: ['latest', '2023.2.3', '2024.1.4']
       fail-fast: false
     steps:
-      - name: Determine versions
-        id: determine-versions
+      - name: Determine PsychoPy version
         run: |
-          get_latest_pypi_version() {
-            local package_name=$1
-            local latest_version
-            latest_version=$(curl -s https://pypi.org/pypi/"$package_name"/json | jq -r .info.version)
-            echo "$latest_version"
-          }
-          
-          # Determine PsychoPy version
-          if [ "${{ matrix.psychopy_version }}" == "latest" ]; then
-            PSYCHOPY_VERSION_CLEAN=$(get_latest_pypi_version "psychopy" | tr -d ',;')
-          else
-            PSYCHOPY_VERSION_CLEAN=$(echo "${{ matrix.psychopy_version }}" | tr -d ',;')
+          PSYCHOPY_VERSION_CLEAN=${{ matrix.psychopy_version }}
+          if [ "$PSYCHOPY_VERSION_CLEAN" == "latest" ]; then
+            PSYCHOPY_VERSION_CLEAN=$(curl -s https://pypi.org/pypi/psychopy/json | jq -r .info.version)
           fi
-        
-          # Set environment variables and outputs
+          PSYCHOPY_VERSION_CLEAN=$(echo "$PSYCHOPY_VERSION_CLEAN" | tr -d ',;')
           echo "PSYCHOPY_VERSION_CLEAN=$PSYCHOPY_VERSION_CLEAN" >> $GITHUB_ENV
       
       - name: Checkout repository
         uses: actions/checkout@v4
       
-      - name: Make script executable
-        run: chmod +x $GITHUB_WORKSPACE/psychopy_linux_installer
-      
-      - name: create tmp and fix permissions
+      - name: Prepare environment
         run: |
+          sudo chmod +x $GITHUB_WORKSPACE/psychopy_linux_installer
           sudo rm -rf /tmp/*
           sudo rm -rf /tmp_dir
           sudo mkdir /tmp_dir
-          sudo chmod -R 777 /tmp_dir
           sudo chown -R $USER:$USER /tmp_dir
+          cp -rf $GITHUB_WORKSPACE/.github/PsychoPy_tests /tmp_dir/
 
       - name: Run PsychoPy Linux Installer
         id: run-installer
         continue-on-error: true
         run: |
-          ARGS="--python-version=${{ matrix.python_version }} --psychopy-version=${{ matrix.psychopy_version }} --bids-version=latest --install-dir=/tmp_dir --force"
-          $GITHUB_WORKSPACE/psychopy_linux_installer $ARGS | tee /tmp_dir/psychopy_install_output.log
-        shell: bash
-
-      - name: Extract PsychoPy start command
-        id: extract-command
+          ARGS="--python-version=${{ matrix.python_version }} --psychopy-version=${{ matrix.psychopy_version }} --additional-packages=psychopy_bids,seedir --install-dir=/tmp_dir/psychopy --no-versioned-install-dir --force"
+          $GITHUB_WORKSPACE/psychopy_linux_installer $ARGS
+      - name: Verify PsychoPy installation and version
+        id: verify-psychopy
         continue-on-error: true
         run: |
-          PSYCHOPY_COMMAND=$(tail -n 1 /tmp_dir/psychopy_install_output.log)
-          if [[ ! "$PSYCHOPY_COMMAND" =~ .*/psychopy_.*_py_.*/bin/psychopy$ ]]; then
-            echo "Invalid PsychoPy command format: $PSYCHOPY_COMMAND"
+          if ! /tmp_dir/psychopy/bin/psychopy -h &> /dev/null; then
+            echo "PsychoPy help command failed"
             exit 1
           fi
-          sudo chmod -R 777 ${GITHUB_WORKSPACE}
-          sudo chown -R $USER:$USER ${GITHUB_WORKSPACE}
-          PYTHON_VENV="$(dirname "$PSYCHOPY_COMMAND")/python"
-
-          echo "PYTHON_VENV command: $PYTHON_VENV"
-          echo "PYTHON_VENV=$PYTHON_VENV" >> $GITHUB_ENV
-          echo "PsychoPy start command: $PSYCHOPY_COMMAND"
-          echo "PSYCHOPY_COMMAND=$PSYCHOPY_COMMAND" >> $GITHUB_ENV
-
-      - name: Verify PsychoPy installation with --help
-        id: verify-help
-        continue-on-error: true
-        run: ${{ env.PSYCHOPY_COMMAND }} -h
-        shell: bash
-
-      - name: Verify PsychoPy installation with --version
-        id: verify-version
-        continue-on-error: true
-        run: |
-          output=$(${{ env.PSYCHOPY_COMMAND }} -v 2>&1)
-          echo "$output"
-          version_line=$(echo "$output" | grep -E "PsychoPy3, version [0-9]+\.[0-9]+\.[0-9]+")
-          if [ "$output" != "$version_line" ]; then
-            echo "::error::PsychoPy version check failed"
+          
+          if ! /tmp_dir/psychopy/bin/psychopy -v | grep -qE "PsychoPy3, version [0-9]+\.[0-9]+\.[0-9]+"; then
+            echo "PsychoPy version check failed"
             exit 1
           fi
-        shell: bash
-
-      - name: copy psychopy tests to tmp
-        id: copy-tests
-        run: |
-          cp -rf $GITHUB_WORKSPACE/.github/PsychoPy_tests /tmp_dir/
       
       - name: run basic PsychoPy test
         id: psychopy-test
         continue-on-error: true
         run: |
           cd /tmp_dir/PsychoPy_tests
-          ${{ env.PYTHON_VENV }} /tmp_dir/PsychoPy_tests/psychopy_test.py 2>&1 | tee /tmp_dir/PsychoPy_tests/psychopy_test.log
+          /tmp_dir/psychopy/bin/python /tmp_dir/PsychoPy_tests/psychopy_test.py 2>&1 | tee /tmp_dir/PsychoPy_tests/psychopy_test.log
           set -e
           if ! tail -n 1 /tmp_dir/PsychoPy_tests/psychopy_test.log | grep -qE "Trial 3: Elapsed time .* seconds"; then
             echo "::error::PsychoPy test output verification failed"
@@ -136,28 +90,14 @@ jobs:
         id: psychopy-test-extended
         continue-on-error: true
         run: |
-          ${{ env.PYTHON_VENV }} /tmp_dir/PsychoPy_tests/psychopy_test_extended.py
-          set -e
-          if ! grep -qE "Visual Test Passed" /tmp_dir/PsychoPy_tests/psychopy_test_extended.log; then
-            echo "::error::Visual Test Failed"
-            exit 1
-          fi
-          # if ! grep -qE "Audio Test Passed" /tmp_dir/PsychoPy_tests/psychopy_test_extended.log; then
-          #   echo "::error::Audio Test Failed"
-          #   exit 1
-          # fi
-          if ! grep -qE "Keyboard Test Passed" /tmp_dir/PsychoPy_tests/psychopy_test_extended.log; then
-            echo "::error::Keyboard Test Failed"
-            exit 1
-          fi
-          if ! grep -qE "Image Test Passed" /tmp_dir/PsychoPy_tests/psychopy_test_extended.log; then
-            echo "::error::Image Test Failed"
-            exit 1
-          fi
-          if ! grep -qE "Timing Test Passed" /tmp_dir/PsychoPy_tests/psychopy_test_extended.log; then
-            echo "::error::Timing Test Failed"
-            exit 1
-          fi
+          output=$(/tmp_dir/psychopy/bin/python /tmp_dir/PsychoPy_tests/psychopy_test_extended.py)
+          tests=("Visual" "Keyboard" "Image" "Timing")
+          for test in "${tests[@]}"; do
+            if ! echo "$output" | grep -qE "${test} Test Passed"; then
+              echo "::error::${test} Test Failed"
+              exit 1
+            fi
+          done
           echo "All tests passed successfully."
 
       - name: Verify BIDS installation simple
@@ -165,25 +105,17 @@ jobs:
         continue-on-error: true
         run: |
           cd /tmp_dir/PsychoPy_tests/BIDS
-          set +e
-          ${{ env.PYTHON_VENV }} /tmp_dir/PsychoPy_tests/BIDS/bids_test_simple.py 2>&1 | tee /tmp_dir/PsychoPy_tests/BIDS/output_simple.log
-          exit_status=$?
-          set -e
-          if [ $exit_status -ne 0 ]; then
+          if ! /tmp_dir/psychopy/bin/python bids_test_simple.py; then
             echo "::error::BIDS simple test execution failed"
             exit 1
           fi
-      
+    
       - name: Verify BIDS installation exp_handler
         id: verify-bids-handler
         continue-on-error: true
         run: |
           cd /tmp_dir/PsychoPy_tests/BIDS
-          set +e
-          ${{ env.PYTHON_VENV }} /tmp_dir/PsychoPy_tests/BIDS/bids_test_exp_handler.py 2>&1 | tee /tmp_dir/PsychoPy_tests/BIDS/output_exp_handler.log
-          exit_status=$?
-          set -e
-          if [ $exit_status -ne 0 ]; then
+          if ! /tmp_dir/psychopy/bin/python bids_test_exp_handler.py; then
             echo "::error::BIDS exp_handler test execution failed"
             exit 1
           fi
@@ -192,20 +124,16 @@ jobs:
         run: |
           STATUS="❌"
           if [[ "${{ steps.run-installer.outcome }}" == "success" && 
-                "${{ steps.extract-command.outcome }}" == "success" && 
-                "${{ steps.verify-help.outcome }}" == "success" && 
-                "${{ steps.verify-version.outcome }}" == "success" && 
+                "${{ steps.verify.outcome }}" == "success" && 
                 "${{ steps.psychopy-test.outcome }}" == "success" && 
                 "${{ steps.psychopy-test-extended.outcome }}" == "success" && 
-                ( "${{ matrix.bids_version }}" == "None" || "${{ steps.verify-bids.outcome }}" == "success" ) && 
-                ( "${{ matrix.bids_version }}" == "None" || "${{ steps.verify-bids-handler.outcome }}" == "success" ) ]]; then
+                "${{ steps.verify-bids.outcome }}" == "success" && 
+                "${{ steps.verify-bids-handler.outcome }}" == "success"  ]]; then
             STATUS="✅"
           fi
       
-          PSYCHOPY_VERSION_CLEAN=${{ env.PSYCHOPY_VERSION_CLEAN }}
-      
-          RESULT_FILE="/tmp_dir/result-${{ matrix.os }}-${{ matrix.python_version }}-${PSYCHOPY_VERSION_CLEAN}.md"
-          echo "| ${{ matrix.os }} | ${{ matrix.python_version }} | $PSYCHOPY_VERSION_CLEAN | $STATUS |" >> $RESULT_FILE
+          RESULT_FILE="/tmp_dir/result-${{ matrix.os }}-${{ matrix.python_version }}-${{ env.PSYCHOPY_VERSION_CLEAN }}.md"
+          echo "| ${{ matrix.os }} | ${{ matrix.python_version }} | ${{ env.PSYCHOPY_VERSION_CLEAN }} | $STATUS |" >> $RESULT_FILE
           cat $RESULT_FILE
       
       - name: Upload result artifact
@@ -214,13 +142,10 @@ jobs:
           name: result-${{ matrix.os }}-${{ matrix.python_version }}-${{ env.PSYCHOPY_VERSION_CLEAN }}
           path: /tmp_dir/result-${{ matrix.os }}-${{ matrix.python_version }}-${{ env.PSYCHOPY_VERSION_CLEAN }}.md
       
-      - name: cleanup paths
+      - name: Cleanup
+        if: always()
         run: |
-          sudo rm -rf /tmp/*
-          sudo rm -rf /tmp_dir
-          sudo rm -rf ~/Desktop/*
-          sudo rm -rf ~/.local/share/applications/*
-          sudo rm -rf ~/.cache
+          sudo rm -rf /tmp/* /tmp_dir ~/Desktop/* ~/.local/share/applications/*
 
   update-readme:
     needs: run-installer
@@ -246,33 +171,22 @@ jobs:
           path: ./artifacts
           merge-multiple: true
 
-      - name: Create result table
+      - name: Create and save result table
         run: |
-          current_date=$(date '+%Y-%m-%d')
-          echo "### Report generated on $current_date" > results.md
-          echo "### [Link to run results](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> results.md
-          echo "" >> results.md
-          echo "| OS | Python Version | PsychoPy Version | Status |" >> results.md
-          echo "|---|---|---|---|" >> results.md
-          for file in ./artifacts/*.md; do
-            cat "$file" >> results.md
-          done
+          cat << EOF > results.md
+          ### Report generated on $(date '+%Y-%m-%d')
+          ### [Link to run results](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
 
-          # Sort the results by OS, Python Version, PsychoPy Version, and Status
-          {
-            head -n 4 results.md
-            tail -n +5 results.md | sort -t'|' -k2,2 -k3,3 -k4,4 -k5,5
-          } > sorted_results.md
+          | OS | Python Version | PsychoPy Version | Status |
+          |---|---|---|---|
+          EOF
 
-          mv sorted_results.md results.md
+          cat ./artifacts/*.md | sort -t'|' -k2,2 -k3,3 -k4,4 -k5,5 >> results.md
 
-      - name: Save results 
-        run: |
           if [ -s results.md ]; then
             cp results.md .github/installation_results.md
           else
-            echo "results.md is empty; skipping."
-            exit 0
+            echo "::warning::results.md is empty; skipping save."
           fi
       
       - name: Commit and push changes
@@ -285,10 +199,9 @@ jobs:
             git push --force
           fi
   
-  
       - name: Check for failed statuses
         run: |
-          if grep -q "❌" results.md && ! grep -q "✅" results.md; then
+          if grep -q "❌" .github/installation_results.md && ! grep -q "✅" .github/installation_results.md; then
             echo "All entries failed or no successful entries found. Failing the job."
             exit 1
           fi
